/* Generated by Yosys 0.46 (git sha1 e97731b9dda91fa5fa53ed87df7c34163ba59a41, clang++ 17.0.6 -fPIC -O3) */

module \$paramod$1b78d2d521b3f5ebabffb07db7e6e88fe1f0b213\alu (i_data_a, i_data_b, i_op, o_alu_result);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  input [7:0] i_data_a;
  wire [7:0] i_data_a;
  input [7:0] i_data_b;
  wire [7:0] i_data_b;
  input [5:0] i_op;
  wire [5:0] i_op;
  output [7:0] o_alu_result;
  wire [7:0] o_alu_result;
  sky130_fd_sc_hd__inv_2 _163_ (
    .A(i_data_b[1]),
    .Y(_096_)
  );
  sky130_fd_sc_hd__inv_2 _164_ (
    .A(i_data_a[7]),
    .Y(_097_)
  );
  sky130_fd_sc_hd__nor4_2 _165_ (
    .A(i_data_b[5]),
    .B(i_data_b[4]),
    .C(i_data_b[7]),
    .D(i_data_b[6]),
    .Y(_098_)
  );
  sky130_fd_sc_hd__mux2_1 _166_ (
    .A0(i_data_a[4]),
    .A1(i_data_a[5]),
    .S(i_data_b[0]),
    .X(_099_)
  );
  sky130_fd_sc_hd__a21oi_2 _167_ (
    .A1(_098_),
    .A2(_099_),
    .B1(i_data_b[1]),
    .Y(_100_)
  );
  sky130_fd_sc_hd__a21oi_2 _168_ (
    .A1(i_data_a[6]),
    .A2(_098_),
    .B1(i_data_b[0]),
    .Y(_101_)
  );
  sky130_fd_sc_hd__a21oi_2 _169_ (
    .A1(i_data_b[0]),
    .A2(_097_),
    .B1(_101_),
    .Y(_102_)
  );
  sky130_fd_sc_hd__o21bai_2 _170_ (
    .A1(_096_),
    .A2(_102_),
    .B1_N(_100_),
    .Y(_103_)
  );
  sky130_fd_sc_hd__nor2_2 _171_ (
    .A(_097_),
    .B(_098_),
    .Y(_104_)
  );
  sky130_fd_sc_hd__or2_2 _172_ (
    .A(i_data_b[3]),
    .B(_104_),
    .X(_105_)
  );
  sky130_fd_sc_hd__or4_2 _173_ (
    .A(i_op[3]),
    .B(i_op[2]),
    .C(i_op[4]),
    .D(i_op[5]),
    .X(_106_)
  );
  sky130_fd_sc_hd__inv_2 _174_ (
    .A(_106_),
    .Y(_107_)
  );
  sky130_fd_sc_hd__and3_2 _175_ (
    .A(i_op[0]),
    .B(i_op[1]),
    .C(_107_),
    .X(_108_)
  );
  sky130_fd_sc_hd__a21boi_2 _176_ (
    .A1(i_data_b[3]),
    .A2(_097_),
    .B1_N(_108_),
    .Y(_109_)
  );
  sky130_fd_sc_hd__mux4_2 _177_ (
    .A0(i_data_a[0]),
    .A1(i_data_a[1]),
    .A2(i_data_a[2]),
    .A3(i_data_a[3]),
    .S0(i_data_b[0]),
    .S1(i_data_b[1]),
    .X(_110_)
  );
  sky130_fd_sc_hd__nor2_2 _178_ (
    .A(i_data_b[3]),
    .B(i_data_b[2]),
    .Y(_111_)
  );
  sky130_fd_sc_hd__nor2_2 _179_ (
    .A(i_data_b[2]),
    .B(_105_),
    .Y(_112_)
  );
  sky130_fd_sc_hd__a21oi_2 _180_ (
    .A1(_098_),
    .A2(_110_),
    .B1(i_data_b[2]),
    .Y(_113_)
  );
  sky130_fd_sc_hd__a21oi_2 _181_ (
    .A1(i_data_b[2]),
    .A2(_103_),
    .B1(_113_),
    .Y(_114_)
  );
  sky130_fd_sc_hd__o21a_2 _182_ (
    .A1(_105_),
    .A2(_114_),
    .B1(_109_),
    .X(_115_)
  );
  sky130_fd_sc_hd__nand2_2 _183_ (
    .A(i_data_a[7]),
    .B(_098_),
    .Y(_116_)
  );
  sky130_fd_sc_hd__a21o_2 _184_ (
    .A1(i_data_b[0]),
    .A2(_116_),
    .B1(_101_),
    .X(_117_)
  );
  sky130_fd_sc_hd__a21o_2 _185_ (
    .A1(i_data_b[1]),
    .A2(_117_),
    .B1(_100_),
    .X(_118_)
  );
  sky130_fd_sc_hd__nand2b_2 _186_ (
    .A_N(i_op[0]),
    .B(i_op[1]),
    .Y(_119_)
  );
  sky130_fd_sc_hd__nor3_2 _187_ (
    .A(i_data_b[3]),
    .B(_106_),
    .C(_119_),
    .Y(_120_)
  );
  sky130_fd_sc_hd__or3_2 _188_ (
    .A(i_data_b[3]),
    .B(_106_),
    .C(_119_),
    .X(_121_)
  );
  sky130_fd_sc_hd__and4bb_2 _189_ (
    .A_N(i_op[3]),
    .B_N(i_op[4]),
    .C(i_op[5]),
    .D(i_op[2]),
    .X(_122_)
  );
  sky130_fd_sc_hd__or4bb_2 _190_ (
    .A(i_op[3]),
    .B(i_op[4]),
    .C_N(i_op[5]),
    .D_N(i_op[2]),
    .X(_123_)
  );
  sky130_fd_sc_hd__and3b_2 _191_ (
    .A_N(i_op[1]),
    .B(_122_),
    .C(i_op[0]),
    .X(_124_)
  );
  sky130_fd_sc_hd__or4b_2 _192_ (
    .A(i_op[3]),
    .B(i_op[2]),
    .C(i_op[4]),
    .D_N(i_op[5]),
    .X(_125_)
  );
  sky130_fd_sc_hd__nor2_2 _193_ (
    .A(i_op[0]),
    .B(_125_),
    .Y(_126_)
  );
  sky130_fd_sc_hd__or2_2 _194_ (
    .A(_119_),
    .B(_123_),
    .X(_127_)
  );
  sky130_fd_sc_hd__inv_2 _195_ (
    .A(_127_),
    .Y(_128_)
  );
  sky130_fd_sc_hd__o2bb2a_2 _196_ (
    .A1_N(i_data_a[0]),
    .A2_N(i_data_b[0]),
    .B1(_126_),
    .B2(_128_),
    .X(_129_)
  );
  sky130_fd_sc_hd__o22a_2 _197_ (
    .A1(i_data_a[0]),
    .A2(i_data_b[0]),
    .B1(_124_),
    .B2(_129_),
    .X(_130_)
  );
  sky130_fd_sc_hd__nand3_2 _198_ (
    .A(i_op[0]),
    .B(i_op[1]),
    .C(_122_),
    .Y(_131_)
  );
  sky130_fd_sc_hd__nor3_2 _199_ (
    .A(i_data_a[0]),
    .B(i_data_b[0]),
    .C(_131_),
    .Y(_132_)
  );
  sky130_fd_sc_hd__nor3_2 _200_ (
    .A(i_op[0]),
    .B(i_op[1]),
    .C(_123_),
    .Y(_133_)
  );
  sky130_fd_sc_hd__or2_2 _201_ (
    .A(i_data_b[2]),
    .B(_121_),
    .X(_134_)
  );
  sky130_fd_sc_hd__a311o_2 _202_ (
    .A1(i_data_a[0]),
    .A2(i_data_b[0]),
    .A3(_133_),
    .B1(_132_),
    .C1(_130_),
    .X(_135_)
  );
  sky130_fd_sc_hd__a211o_2 _203_ (
    .A1(i_data_b[2]),
    .A2(_118_),
    .B1(_121_),
    .C1(_113_),
    .X(_136_)
  );
  sky130_fd_sc_hd__or3b_2 _204_ (
    .A(_115_),
    .B(_135_),
    .C_N(_136_),
    .X(o_alu_result[0])
  );
  sky130_fd_sc_hd__or2_2 _205_ (
    .A(_119_),
    .B(_125_),
    .X(_137_)
  );
  sky130_fd_sc_hd__o21a_2 _206_ (
    .A1(_119_),
    .A2(_125_),
    .B1(i_data_b[0]),
    .X(_138_)
  );
  sky130_fd_sc_hd__xnor2_2 _207_ (
    .A(i_data_b[1]),
    .B(_138_),
    .Y(_139_)
  );
  sky130_fd_sc_hd__and2_2 _208_ (
    .A(i_data_a[1]),
    .B(_139_),
    .X(_140_)
  );
  sky130_fd_sc_hd__xor2_2 _209_ (
    .A(i_data_a[1]),
    .B(_139_),
    .X(_141_)
  );
  sky130_fd_sc_hd__nand2b_2 _210_ (
    .A_N(i_data_a[0]),
    .B(i_data_b[0]),
    .Y(_142_)
  );
  sky130_fd_sc_hd__nand2_2 _211_ (
    .A(_141_),
    .B(_142_),
    .Y(_143_)
  );
  sky130_fd_sc_hd__o21a_2 _212_ (
    .A1(_141_),
    .A2(_142_),
    .B1(_126_),
    .X(_144_)
  );
  sky130_fd_sc_hd__a21oi_2 _213_ (
    .A1(i_data_a[1]),
    .A2(i_data_b[1]),
    .B1(_127_),
    .Y(_145_)
  );
  sky130_fd_sc_hd__o22a_2 _214_ (
    .A1(i_data_a[1]),
    .A2(i_data_b[1]),
    .B1(_124_),
    .B2(_145_),
    .X(_146_)
  );
  sky130_fd_sc_hd__nor3_2 _215_ (
    .A(i_data_a[1]),
    .B(i_data_b[1]),
    .C(_131_),
    .Y(_147_)
  );
  sky130_fd_sc_hd__a311o_2 _216_ (
    .A1(i_data_a[1]),
    .A2(i_data_b[1]),
    .A3(_133_),
    .B1(_146_),
    .C1(_147_),
    .X(_148_)
  );
  sky130_fd_sc_hd__mux2_1 _217_ (
    .A0(i_data_a[3]),
    .A1(i_data_a[4]),
    .S(i_data_b[0]),
    .X(_149_)
  );
  sky130_fd_sc_hd__mux2_1 _218_ (
    .A0(i_data_a[1]),
    .A1(i_data_a[2]),
    .S(i_data_b[0]),
    .X(_150_)
  );
  sky130_fd_sc_hd__a31o_2 _219_ (
    .A1(i_data_b[1]),
    .A2(_098_),
    .A3(_149_),
    .B1(i_data_b[2]),
    .X(_151_)
  );
  sky130_fd_sc_hd__a31o_2 _220_ (
    .A1(_096_),
    .A2(_098_),
    .A3(_150_),
    .B1(_151_),
    .X(_152_)
  );
  sky130_fd_sc_hd__mux2_1 _221_ (
    .A0(i_data_a[5]),
    .A1(i_data_a[6]),
    .S(i_data_b[0]),
    .X(_153_)
  );
  sky130_fd_sc_hd__and2_2 _222_ (
    .A(_098_),
    .B(_153_),
    .X(_154_)
  );
  sky130_fd_sc_hd__nand2_2 _223_ (
    .A(i_data_b[1]),
    .B(_097_),
    .Y(_155_)
  );
  sky130_fd_sc_hd__o21ai_2 _224_ (
    .A1(i_data_b[1]),
    .A2(_154_),
    .B1(_155_),
    .Y(_156_)
  );
  sky130_fd_sc_hd__a21boi_2 _225_ (
    .A1(i_data_b[2]),
    .A2(_156_),
    .B1_N(_152_),
    .Y(_157_)
  );
  sky130_fd_sc_hd__o21a_2 _226_ (
    .A1(_105_),
    .A2(_157_),
    .B1(_109_),
    .X(_158_)
  );
  sky130_fd_sc_hd__o21ai_2 _227_ (
    .A1(i_data_b[0]),
    .A2(_116_),
    .B1(i_data_b[1]),
    .Y(_159_)
  );
  sky130_fd_sc_hd__o21ai_2 _228_ (
    .A1(i_data_b[1]),
    .A2(_154_),
    .B1(_159_),
    .Y(_160_)
  );
  sky130_fd_sc_hd__nand2_2 _229_ (
    .A(i_data_b[2]),
    .B(_160_),
    .Y(_161_)
  );
  sky130_fd_sc_hd__a211o_2 _230_ (
    .A1(_143_),
    .A2(_144_),
    .B1(_148_),
    .C1(_158_),
    .X(_162_)
  );
  sky130_fd_sc_hd__a31o_2 _231_ (
    .A1(_120_),
    .A2(_152_),
    .A3(_161_),
    .B1(_162_),
    .X(o_alu_result[1])
  );
  sky130_fd_sc_hd__o22a_2 _232_ (
    .A1(i_data_b[0]),
    .A2(i_data_b[1]),
    .B1(_119_),
    .B2(_125_),
    .X(_000_)
  );
  sky130_fd_sc_hd__xnor2_2 _233_ (
    .A(i_data_b[2]),
    .B(_000_),
    .Y(_001_)
  );
  sky130_fd_sc_hd__nand2_2 _234_ (
    .A(i_data_a[2]),
    .B(_001_),
    .Y(_002_)
  );
  sky130_fd_sc_hd__or2_2 _235_ (
    .A(i_data_a[2]),
    .B(_001_),
    .X(_003_)
  );
  sky130_fd_sc_hd__nand2_2 _236_ (
    .A(_002_),
    .B(_003_),
    .Y(_004_)
  );
  sky130_fd_sc_hd__a21oi_2 _237_ (
    .A1(_141_),
    .A2(_142_),
    .B1(_140_),
    .Y(_005_)
  );
  sky130_fd_sc_hd__nor2_2 _238_ (
    .A(_004_),
    .B(_005_),
    .Y(_006_)
  );
  sky130_fd_sc_hd__a21bo_2 _239_ (
    .A1(_004_),
    .A2(_005_),
    .B1_N(_126_),
    .X(_007_)
  );
  sky130_fd_sc_hd__mux4_2 _240_ (
    .A0(i_data_a[2]),
    .A1(i_data_a[3]),
    .A2(i_data_a[4]),
    .A3(i_data_a[5]),
    .S0(i_data_b[0]),
    .S1(i_data_b[1]),
    .X(_008_)
  );
  sky130_fd_sc_hd__nand2_2 _241_ (
    .A(_098_),
    .B(_008_),
    .Y(_009_)
  );
  sky130_fd_sc_hd__o31a_2 _242_ (
    .A1(i_data_b[1]),
    .A2(_102_),
    .A3(_104_),
    .B1(_155_),
    .X(_010_)
  );
  sky130_fd_sc_hd__or3b_2 _243_ (
    .A(i_data_b[3]),
    .B(_010_),
    .C_N(i_data_b[2]),
    .X(_011_)
  );
  sky130_fd_sc_hd__nand2_2 _244_ (
    .A(_109_),
    .B(_011_),
    .Y(_012_)
  );
  sky130_fd_sc_hd__or4b_2 _245_ (
    .A(i_data_b[1]),
    .B(_117_),
    .C(_121_),
    .D_N(i_data_b[2]),
    .X(_013_)
  );
  sky130_fd_sc_hd__a22o_2 _246_ (
    .A1(_112_),
    .A2(_009_),
    .B1(_012_),
    .B2(_013_),
    .X(_014_)
  );
  sky130_fd_sc_hd__a21oi_2 _247_ (
    .A1(i_data_b[2]),
    .A2(i_data_a[2]),
    .B1(_127_),
    .Y(_015_)
  );
  sky130_fd_sc_hd__o22ai_2 _248_ (
    .A1(i_data_b[2]),
    .A2(i_data_a[2]),
    .B1(_124_),
    .B2(_015_),
    .Y(_016_)
  );
  sky130_fd_sc_hd__nand3_2 _249_ (
    .A(i_data_b[2]),
    .B(i_data_a[2]),
    .C(_133_),
    .Y(_017_)
  );
  sky130_fd_sc_hd__o31a_2 _250_ (
    .A1(i_data_b[2]),
    .A2(i_data_a[2]),
    .A3(_131_),
    .B1(_017_),
    .X(_018_)
  );
  sky130_fd_sc_hd__o2111a_2 _251_ (
    .A1(_134_),
    .A2(_009_),
    .B1(_014_),
    .C1(_016_),
    .D1(_018_),
    .X(_019_)
  );
  sky130_fd_sc_hd__o21ai_2 _252_ (
    .A1(_006_),
    .A2(_007_),
    .B1(_019_),
    .Y(o_alu_result[2])
  );
  sky130_fd_sc_hd__o21a_2 _253_ (
    .A1(_004_),
    .A2(_005_),
    .B1(_002_),
    .X(_020_)
  );
  sky130_fd_sc_hd__o32a_2 _254_ (
    .A1(i_data_b[0]),
    .A2(i_data_b[2]),
    .A3(i_data_b[1]),
    .B1(_119_),
    .B2(_125_),
    .X(_021_)
  );
  sky130_fd_sc_hd__xnor2_2 _255_ (
    .A(i_data_b[3]),
    .B(_021_),
    .Y(_022_)
  );
  sky130_fd_sc_hd__xor2_2 _256_ (
    .A(i_data_a[3]),
    .B(_022_),
    .X(_023_)
  );
  sky130_fd_sc_hd__inv_2 _257_ (
    .A(_023_),
    .Y(_024_)
  );
  sky130_fd_sc_hd__xnor2_2 _258_ (
    .A(_020_),
    .B(_023_),
    .Y(_025_)
  );
  sky130_fd_sc_hd__a31o_2 _259_ (
    .A1(_096_),
    .A2(_098_),
    .A3(_149_),
    .B1(i_data_b[2]),
    .X(_026_)
  );
  sky130_fd_sc_hd__a21o_2 _260_ (
    .A1(i_data_b[1]),
    .A2(_154_),
    .B1(_026_),
    .X(_027_)
  );
  sky130_fd_sc_hd__or2_2 _261_ (
    .A(_105_),
    .B(_027_),
    .X(_028_)
  );
  sky130_fd_sc_hd__o21ai_2 _262_ (
    .A1(i_data_a[7]),
    .A2(_111_),
    .B1(_108_),
    .Y(_029_)
  );
  sky130_fd_sc_hd__inv_2 _263_ (
    .A(_029_),
    .Y(_030_)
  );
  sky130_fd_sc_hd__a21oi_2 _264_ (
    .A1(i_data_b[3]),
    .A2(i_data_a[3]),
    .B1(_127_),
    .Y(_031_)
  );
  sky130_fd_sc_hd__o22a_2 _265_ (
    .A1(i_data_b[3]),
    .A2(i_data_a[3]),
    .B1(_124_),
    .B2(_031_),
    .X(_032_)
  );
  sky130_fd_sc_hd__nor3_2 _266_ (
    .A(i_data_b[3]),
    .B(i_data_a[3]),
    .C(_131_),
    .Y(_033_)
  );
  sky130_fd_sc_hd__a311o_2 _267_ (
    .A1(i_data_b[3]),
    .A2(i_data_a[3]),
    .A3(_133_),
    .B1(_032_),
    .C1(_033_),
    .X(_034_)
  );
  sky130_fd_sc_hd__o31ai_2 _268_ (
    .A1(i_data_b[0]),
    .A2(i_data_b[1]),
    .A3(_116_),
    .B1(i_data_b[2]),
    .Y(_035_)
  );
  sky130_fd_sc_hd__a32o_2 _269_ (
    .A1(_120_),
    .A2(_027_),
    .A3(_035_),
    .B1(_126_),
    .B2(_025_),
    .X(_036_)
  );
  sky130_fd_sc_hd__a211o_2 _270_ (
    .A1(_028_),
    .A2(_030_),
    .B1(_034_),
    .C1(_036_),
    .X(o_alu_result[3])
  );
  sky130_fd_sc_hd__or4_2 _271_ (
    .A(i_data_b[0]),
    .B(i_data_b[3]),
    .C(i_data_b[2]),
    .D(i_data_b[1]),
    .X(_037_)
  );
  sky130_fd_sc_hd__nand2_2 _272_ (
    .A(_137_),
    .B(_037_),
    .Y(_038_)
  );
  sky130_fd_sc_hd__xor2_2 _273_ (
    .A(i_data_b[4]),
    .B(_038_),
    .X(_039_)
  );
  sky130_fd_sc_hd__nand2_2 _274_ (
    .A(i_data_a[4]),
    .B(_039_),
    .Y(_040_)
  );
  sky130_fd_sc_hd__or2_2 _275_ (
    .A(i_data_a[4]),
    .B(_039_),
    .X(_041_)
  );
  sky130_fd_sc_hd__and2_2 _276_ (
    .A(_040_),
    .B(_041_),
    .X(_042_)
  );
  sky130_fd_sc_hd__a22o_2 _277_ (
    .A1(i_data_a[2]),
    .A2(_001_),
    .B1(_022_),
    .B2(i_data_a[3]),
    .X(_043_)
  );
  sky130_fd_sc_hd__o21ai_2 _278_ (
    .A1(i_data_a[3]),
    .A2(_022_),
    .B1(_043_),
    .Y(_044_)
  );
  sky130_fd_sc_hd__o31ai_2 _279_ (
    .A1(_004_),
    .A2(_005_),
    .A3(_024_),
    .B1(_044_),
    .Y(_045_)
  );
  sky130_fd_sc_hd__or2_2 _280_ (
    .A(_042_),
    .B(_045_),
    .X(_046_)
  );
  sky130_fd_sc_hd__nand2_2 _281_ (
    .A(_042_),
    .B(_045_),
    .Y(_047_)
  );
  sky130_fd_sc_hd__a21oi_2 _282_ (
    .A1(_103_),
    .A2(_112_),
    .B1(_029_),
    .Y(_048_)
  );
  sky130_fd_sc_hd__nand3_2 _283_ (
    .A(i_data_b[4]),
    .B(i_data_a[4]),
    .C(_133_),
    .Y(_049_)
  );
  sky130_fd_sc_hd__a21oi_2 _284_ (
    .A1(i_data_b[4]),
    .A2(i_data_a[4]),
    .B1(_127_),
    .Y(_050_)
  );
  sky130_fd_sc_hd__o22ai_2 _285_ (
    .A1(i_data_b[4]),
    .A2(i_data_a[4]),
    .B1(_124_),
    .B2(_050_),
    .Y(_051_)
  );
  sky130_fd_sc_hd__o311a_2 _286_ (
    .A1(i_data_b[4]),
    .A2(i_data_a[4]),
    .A3(_131_),
    .B1(_049_),
    .C1(_051_),
    .X(_052_)
  );
  sky130_fd_sc_hd__o21ai_2 _287_ (
    .A1(_118_),
    .A2(_134_),
    .B1(_052_),
    .Y(_053_)
  );
  sky130_fd_sc_hd__a311o_2 _288_ (
    .A1(_126_),
    .A2(_046_),
    .A3(_047_),
    .B1(_048_),
    .C1(_053_),
    .X(o_alu_result[4])
  );
  sky130_fd_sc_hd__o21a_2 _289_ (
    .A1(i_data_b[4]),
    .A2(_037_),
    .B1(_137_),
    .X(_054_)
  );
  sky130_fd_sc_hd__xnor2_2 _290_ (
    .A(i_data_b[5]),
    .B(_054_),
    .Y(_055_)
  );
  sky130_fd_sc_hd__nand2_2 _291_ (
    .A(i_data_a[5]),
    .B(_055_),
    .Y(_056_)
  );
  sky130_fd_sc_hd__inv_2 _292_ (
    .A(_056_),
    .Y(_057_)
  );
  sky130_fd_sc_hd__nor2_2 _293_ (
    .A(i_data_a[5]),
    .B(_055_),
    .Y(_058_)
  );
  sky130_fd_sc_hd__o211a_2 _294_ (
    .A1(_057_),
    .A2(_058_),
    .B1(_040_),
    .C1(_047_),
    .X(_059_)
  );
  sky130_fd_sc_hd__a211o_2 _295_ (
    .A1(_040_),
    .A2(_047_),
    .B1(_057_),
    .C1(_058_),
    .X(_060_)
  );
  sky130_fd_sc_hd__nand2_2 _296_ (
    .A(_126_),
    .B(_060_),
    .Y(_061_)
  );
  sky130_fd_sc_hd__a21o_2 _297_ (
    .A1(_112_),
    .A2(_156_),
    .B1(_029_),
    .X(_062_)
  );
  sky130_fd_sc_hd__a21oi_2 _298_ (
    .A1(i_data_b[5]),
    .A2(i_data_a[5]),
    .B1(_127_),
    .Y(_063_)
  );
  sky130_fd_sc_hd__o22a_2 _299_ (
    .A1(i_data_b[5]),
    .A2(i_data_a[5]),
    .B1(_124_),
    .B2(_063_),
    .X(_064_)
  );
  sky130_fd_sc_hd__or3_2 _300_ (
    .A(i_data_b[5]),
    .B(i_data_a[5]),
    .C(_131_),
    .X(_065_)
  );
  sky130_fd_sc_hd__a31oi_2 _301_ (
    .A1(i_data_b[5]),
    .A2(i_data_a[5]),
    .A3(_133_),
    .B1(_064_),
    .Y(_066_)
  );
  sky130_fd_sc_hd__o2111a_2 _302_ (
    .A1(_134_),
    .A2(_160_),
    .B1(_062_),
    .C1(_065_),
    .D1(_066_),
    .X(_067_)
  );
  sky130_fd_sc_hd__o21ai_2 _303_ (
    .A1(_059_),
    .A2(_061_),
    .B1(_067_),
    .Y(o_alu_result[5])
  );
  sky130_fd_sc_hd__a21o_2 _304_ (
    .A1(i_data_b[5]),
    .A2(_137_),
    .B1(_054_),
    .X(_068_)
  );
  sky130_fd_sc_hd__xnor2_2 _305_ (
    .A(i_data_b[6]),
    .B(_068_),
    .Y(_069_)
  );
  sky130_fd_sc_hd__nand2_2 _306_ (
    .A(i_data_a[6]),
    .B(_069_),
    .Y(_070_)
  );
  sky130_fd_sc_hd__or2_2 _307_ (
    .A(i_data_a[6]),
    .B(_069_),
    .X(_071_)
  );
  sky130_fd_sc_hd__nand2_2 _308_ (
    .A(_070_),
    .B(_071_),
    .Y(_072_)
  );
  sky130_fd_sc_hd__a31o_2 _309_ (
    .A1(_040_),
    .A2(_047_),
    .A3(_056_),
    .B1(_058_),
    .X(_073_)
  );
  sky130_fd_sc_hd__nand2_2 _310_ (
    .A(_072_),
    .B(_073_),
    .Y(_074_)
  );
  sky130_fd_sc_hd__a311o_2 _311_ (
    .A1(_040_),
    .A2(_047_),
    .A3(_056_),
    .B1(_058_),
    .C1(_072_),
    .X(_075_)
  );
  sky130_fd_sc_hd__o31a_2 _312_ (
    .A1(i_data_b[3]),
    .A2(i_data_b[2]),
    .A3(_010_),
    .B1(_030_),
    .X(_076_)
  );
  sky130_fd_sc_hd__a21oi_2 _313_ (
    .A1(i_data_b[6]),
    .A2(i_data_a[6]),
    .B1(_127_),
    .Y(_077_)
  );
  sky130_fd_sc_hd__o22a_2 _314_ (
    .A1(i_data_b[6]),
    .A2(i_data_a[6]),
    .B1(_124_),
    .B2(_077_),
    .X(_078_)
  );
  sky130_fd_sc_hd__nor3_2 _315_ (
    .A(i_data_b[6]),
    .B(i_data_a[6]),
    .C(_131_),
    .Y(_079_)
  );
  sky130_fd_sc_hd__a31o_2 _316_ (
    .A1(i_data_b[6]),
    .A2(i_data_a[6]),
    .A3(_133_),
    .B1(_079_),
    .X(_080_)
  );
  sky130_fd_sc_hd__or3_2 _317_ (
    .A(i_data_b[1]),
    .B(_117_),
    .C(_134_),
    .X(_081_)
  );
  sky130_fd_sc_hd__or4b_2 _318_ (
    .A(_076_),
    .B(_078_),
    .C(_080_),
    .D_N(_081_),
    .X(_082_)
  );
  sky130_fd_sc_hd__a31o_2 _319_ (
    .A1(_126_),
    .A2(_074_),
    .A3(_075_),
    .B1(_082_),
    .X(o_alu_result[6])
  );
  sky130_fd_sc_hd__nor2_2 _320_ (
    .A(i_data_b[7]),
    .B(i_data_a[7]),
    .Y(_083_)
  );
  sky130_fd_sc_hd__and2_2 _321_ (
    .A(i_data_b[7]),
    .B(i_data_a[7]),
    .X(_084_)
  );
  sky130_fd_sc_hd__or2_2 _322_ (
    .A(_083_),
    .B(_084_),
    .X(_085_)
  );
  sky130_fd_sc_hd__o41a_2 _323_ (
    .A1(i_data_b[5]),
    .A2(i_data_b[4]),
    .A3(i_data_b[6]),
    .A4(_037_),
    .B1(_137_),
    .X(_086_)
  );
  sky130_fd_sc_hd__xor2_2 _324_ (
    .A(_085_),
    .B(_086_),
    .X(_087_)
  );
  sky130_fd_sc_hd__nand3b_2 _325_ (
    .A_N(_087_),
    .B(_075_),
    .C(_070_),
    .Y(_088_)
  );
  sky130_fd_sc_hd__a21bo_2 _326_ (
    .A1(_070_),
    .A2(_075_),
    .B1_N(_087_),
    .X(_089_)
  );
  sky130_fd_sc_hd__a211oi_2 _327_ (
    .A1(i_data_a[7]),
    .A2(_108_),
    .B1(_124_),
    .C1(_083_),
    .Y(_090_)
  );
  sky130_fd_sc_hd__a21oi_2 _328_ (
    .A1(_131_),
    .A2(_083_),
    .B1(_090_),
    .Y(_091_)
  );
  sky130_fd_sc_hd__nor2_2 _329_ (
    .A(_127_),
    .B(_085_),
    .Y(_092_)
  );
  sky130_fd_sc_hd__a31o_2 _330_ (
    .A1(i_data_b[7]),
    .A2(i_data_a[7]),
    .A3(_133_),
    .B1(_092_),
    .X(_093_)
  );
  sky130_fd_sc_hd__or4_2 _331_ (
    .A(i_data_b[0]),
    .B(i_data_b[1]),
    .C(_116_),
    .D(_134_),
    .X(_094_)
  );
  sky130_fd_sc_hd__or3b_2 _332_ (
    .A(_091_),
    .B(_093_),
    .C_N(_094_),
    .X(_095_)
  );
  sky130_fd_sc_hd__a31o_2 _333_ (
    .A1(_126_),
    .A2(_088_),
    .A3(_089_),
    .B1(_095_),
    .X(o_alu_result[7])
  );
endmodule

module \$paramod$3657eea4d53669bfdbf8ea094d48a5708f5ac2cf\alu_uart_interface (i_clk, i_reset, i_alu_result, i_data_to_read, i_fifo_rx_empty, i_fifo_tx_full, o_fifo_rx_read, o_fifo_tx_write, o_data_to_write, o_alu_opcode, o_alu_op_A, o_alu_op_B);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  input [7:0] i_alu_result;
  wire [7:0] i_alu_result;
  input i_clk;
  wire i_clk;
  input [7:0] i_data_to_read;
  wire [7:0] i_data_to_read;
  input i_fifo_rx_empty;
  wire i_fifo_rx_empty;
  input i_fifo_tx_full;
  wire i_fifo_tx_full;
  input i_reset;
  wire i_reset;
  output [7:0] o_alu_op_A;
  wire [7:0] o_alu_op_A;
  output [7:0] o_alu_op_B;
  wire [7:0] o_alu_op_B;
  output [5:0] o_alu_opcode;
  wire [5:0] o_alu_opcode;
  output [7:0] o_data_to_write;
  wire [7:0] o_data_to_write;
  output o_fifo_rx_read;
  wire o_fifo_rx_read;
  output o_fifo_tx_write;
  wire o_fifo_tx_write;
  wire \state[0] ;
  wire \state[1] ;
  wire \state[2] ;
  wire \state[3] ;
  wire \wait_reg[0] ;
  wire \wait_reg[1] ;
  sky130_fd_sc_hd__inv_2 _094_ (
    .A(\state[3] ),
    .Y(_090_)
  );
  sky130_fd_sc_hd__inv_2 _095_ (
    .A(i_fifo_rx_empty),
    .Y(_091_)
  );
  sky130_fd_sc_hd__inv_2 _096_ (
    .A(i_reset),
    .Y(_092_)
  );
  sky130_fd_sc_hd__nor2_2 _097_ (
    .A(\state[3] ),
    .B(\state[2] ),
    .Y(_093_)
  );
  sky130_fd_sc_hd__or4b_2 _098_ (
    .A(\state[3] ),
    .B(\state[2] ),
    .C(\state[0] ),
    .D_N(\state[1] ),
    .X(_038_)
  );
  sky130_fd_sc_hd__and3_2 _099_ (
    .A(\state[1] ),
    .B(i_fifo_rx_empty),
    .C(_093_),
    .X(_039_)
  );
  sky130_fd_sc_hd__or2_2 _100_ (
    .A(\state[1] ),
    .B(\state[0] ),
    .X(_040_)
  );
  sky130_fd_sc_hd__and3_2 _101_ (
    .A(i_fifo_rx_empty),
    .B(_093_),
    .C(_040_),
    .X(_041_)
  );
  sky130_fd_sc_hd__o221a_2 _102_ (
    .A1(_091_),
    .A2(_038_),
    .B1(_041_),
    .B2(\wait_reg[0] ),
    .C1(_092_),
    .X(_000_)
  );
  sky130_fd_sc_hd__and2b_2 _103_ (
    .A_N(_041_),
    .B(\wait_reg[1] ),
    .X(_042_)
  );
  sky130_fd_sc_hd__o21a_2 _104_ (
    .A1(_039_),
    .A2(_042_),
    .B1(_092_),
    .X(_001_)
  );
  sky130_fd_sc_hd__nor2_2 _105_ (
    .A(i_fifo_rx_empty),
    .B(_038_),
    .Y(_043_)
  );
  sky130_fd_sc_hd__or2_2 _106_ (
    .A(i_fifo_rx_empty),
    .B(_038_),
    .X(_044_)
  );
  sky130_fd_sc_hd__nor3_2 _107_ (
    .A(\state[2] ),
    .B(\state[1] ),
    .C(\state[0] ),
    .Y(_045_)
  );
  sky130_fd_sc_hd__o21a_2 _108_ (
    .A1(_090_),
    .A2(\wait_reg[0] ),
    .B1(_045_),
    .X(_046_)
  );
  sky130_fd_sc_hd__nor4b_2 _109_ (
    .A(\state[3] ),
    .B(\state[1] ),
    .C(\state[0] ),
    .D_N(\state[2] ),
    .Y(_047_)
  );
  sky130_fd_sc_hd__a22o_2 _110_ (
    .A1(i_fifo_rx_empty),
    .A2(_045_),
    .B1(_047_),
    .B2(i_fifo_tx_full),
    .X(_048_)
  );
  sky130_fd_sc_hd__nor2_2 _111_ (
    .A(i_reset),
    .B(_048_),
    .Y(_049_)
  );
  sky130_fd_sc_hd__o21a_2 _112_ (
    .A1(_043_),
    .A2(_046_),
    .B1(_049_),
    .X(_002_)
  );
  sky130_fd_sc_hd__or4b_2 _113_ (
    .A(\state[3] ),
    .B(\state[2] ),
    .C(\state[1] ),
    .D_N(\state[0] ),
    .X(_050_)
  );
  sky130_fd_sc_hd__nor2_2 _114_ (
    .A(i_fifo_rx_empty),
    .B(_050_),
    .Y(_051_)
  );
  sky130_fd_sc_hd__a31o_2 _115_ (
    .A1(\state[3] ),
    .A2(\wait_reg[1] ),
    .A3(_045_),
    .B1(_051_),
    .X(_052_)
  );
  sky130_fd_sc_hd__o21a_2 _116_ (
    .A1(_043_),
    .A2(_052_),
    .B1(_049_),
    .X(_003_)
  );
  sky130_fd_sc_hd__and4_2 _117_ (
    .A(\state[1] ),
    .B(\state[0] ),
    .C(_091_),
    .D(_093_),
    .X(_053_)
  );
  sky130_fd_sc_hd__a32o_2 _118_ (
    .A1(i_fifo_tx_full),
    .A2(_092_),
    .A3(_047_),
    .B1(_049_),
    .B2(_053_),
    .X(_004_)
  );
  sky130_fd_sc_hd__nand2_2 _119_ (
    .A(_090_),
    .B(_048_),
    .Y(_054_)
  );
  sky130_fd_sc_hd__o211a_2 _120_ (
    .A1(_041_),
    .A2(_048_),
    .B1(_054_),
    .C1(_092_),
    .X(_005_)
  );
  sky130_fd_sc_hd__a21o_2 _121_ (
    .A1(i_fifo_rx_empty),
    .A2(_045_),
    .B1(_047_),
    .X(_055_)
  );
  sky130_fd_sc_hd__o211a_2 _122_ (
    .A1(\state[2] ),
    .A2(_040_),
    .B1(_050_),
    .C1(_038_),
    .X(_056_)
  );
  sky130_fd_sc_hd__o2bb2a_2 _123_ (
    .A1_N(o_fifo_rx_read),
    .A2_N(_055_),
    .B1(_056_),
    .B2(i_fifo_rx_empty),
    .X(_057_)
  );
  sky130_fd_sc_hd__nor2_2 _124_ (
    .A(i_reset),
    .B(_057_),
    .Y(_006_)
  );
  sky130_fd_sc_hd__a221o_2 _125_ (
    .A1(_093_),
    .A2(_040_),
    .B1(_045_),
    .B2(\state[3] ),
    .C1(_047_),
    .X(_058_)
  );
  sky130_fd_sc_hd__and2b_2 _126_ (
    .A_N(i_fifo_tx_full),
    .B(_047_),
    .X(_059_)
  );
  sky130_fd_sc_hd__o211a_2 _127_ (
    .A1(o_fifo_tx_write),
    .A2(_059_),
    .B1(_058_),
    .C1(_092_),
    .X(_007_)
  );
  sky130_fd_sc_hd__or3_2 _128_ (
    .A(i_data_to_read[0]),
    .B(i_fifo_rx_empty),
    .C(_050_),
    .X(_060_)
  );
  sky130_fd_sc_hd__o211a_2 _129_ (
    .A1(o_alu_opcode[0]),
    .A2(_051_),
    .B1(_060_),
    .C1(_092_),
    .X(_008_)
  );
  sky130_fd_sc_hd__or3_2 _130_ (
    .A(i_data_to_read[1]),
    .B(i_fifo_rx_empty),
    .C(_050_),
    .X(_061_)
  );
  sky130_fd_sc_hd__o211a_2 _131_ (
    .A1(o_alu_opcode[1]),
    .A2(_051_),
    .B1(_061_),
    .C1(_092_),
    .X(_009_)
  );
  sky130_fd_sc_hd__or3_2 _132_ (
    .A(i_data_to_read[2]),
    .B(i_fifo_rx_empty),
    .C(_050_),
    .X(_062_)
  );
  sky130_fd_sc_hd__o211a_2 _133_ (
    .A1(o_alu_opcode[2]),
    .A2(_051_),
    .B1(_062_),
    .C1(_092_),
    .X(_010_)
  );
  sky130_fd_sc_hd__or3_2 _134_ (
    .A(i_data_to_read[3]),
    .B(i_fifo_rx_empty),
    .C(_050_),
    .X(_063_)
  );
  sky130_fd_sc_hd__o211a_2 _135_ (
    .A1(o_alu_opcode[3]),
    .A2(_051_),
    .B1(_063_),
    .C1(_092_),
    .X(_011_)
  );
  sky130_fd_sc_hd__or3_2 _136_ (
    .A(i_data_to_read[4]),
    .B(i_fifo_rx_empty),
    .C(_050_),
    .X(_064_)
  );
  sky130_fd_sc_hd__o211a_2 _137_ (
    .A1(o_alu_opcode[4]),
    .A2(_051_),
    .B1(_064_),
    .C1(_092_),
    .X(_012_)
  );
  sky130_fd_sc_hd__or3_2 _138_ (
    .A(i_data_to_read[5]),
    .B(i_fifo_rx_empty),
    .C(_050_),
    .X(_065_)
  );
  sky130_fd_sc_hd__o211a_2 _139_ (
    .A1(o_alu_opcode[5]),
    .A2(_051_),
    .B1(_065_),
    .C1(_092_),
    .X(_013_)
  );
  sky130_fd_sc_hd__or2_2 _140_ (
    .A(i_data_to_read[0]),
    .B(_044_),
    .X(_066_)
  );
  sky130_fd_sc_hd__o211a_2 _141_ (
    .A1(o_alu_op_A[0]),
    .A2(_043_),
    .B1(_066_),
    .C1(_092_),
    .X(_014_)
  );
  sky130_fd_sc_hd__or2_2 _142_ (
    .A(i_data_to_read[1]),
    .B(_044_),
    .X(_067_)
  );
  sky130_fd_sc_hd__o211a_2 _143_ (
    .A1(o_alu_op_A[1]),
    .A2(_043_),
    .B1(_067_),
    .C1(_092_),
    .X(_015_)
  );
  sky130_fd_sc_hd__or2_2 _144_ (
    .A(i_data_to_read[2]),
    .B(_044_),
    .X(_068_)
  );
  sky130_fd_sc_hd__o211a_2 _145_ (
    .A1(o_alu_op_A[2]),
    .A2(_043_),
    .B1(_068_),
    .C1(_092_),
    .X(_016_)
  );
  sky130_fd_sc_hd__or2_2 _146_ (
    .A(i_data_to_read[3]),
    .B(_044_),
    .X(_069_)
  );
  sky130_fd_sc_hd__o211a_2 _147_ (
    .A1(o_alu_op_A[3]),
    .A2(_043_),
    .B1(_069_),
    .C1(_092_),
    .X(_017_)
  );
  sky130_fd_sc_hd__or2_2 _148_ (
    .A(i_data_to_read[4]),
    .B(_044_),
    .X(_070_)
  );
  sky130_fd_sc_hd__o211a_2 _149_ (
    .A1(o_alu_op_A[4]),
    .A2(_043_),
    .B1(_070_),
    .C1(_092_),
    .X(_018_)
  );
  sky130_fd_sc_hd__or2_2 _150_ (
    .A(i_data_to_read[5]),
    .B(_044_),
    .X(_071_)
  );
  sky130_fd_sc_hd__o211a_2 _151_ (
    .A1(o_alu_op_A[5]),
    .A2(_043_),
    .B1(_071_),
    .C1(_092_),
    .X(_019_)
  );
  sky130_fd_sc_hd__or2_2 _152_ (
    .A(i_data_to_read[6]),
    .B(_044_),
    .X(_072_)
  );
  sky130_fd_sc_hd__o211a_2 _153_ (
    .A1(o_alu_op_A[6]),
    .A2(_043_),
    .B1(_072_),
    .C1(_092_),
    .X(_020_)
  );
  sky130_fd_sc_hd__or2_2 _154_ (
    .A(i_data_to_read[7]),
    .B(_044_),
    .X(_073_)
  );
  sky130_fd_sc_hd__o211a_2 _155_ (
    .A1(o_alu_op_A[7]),
    .A2(_043_),
    .B1(_073_),
    .C1(_092_),
    .X(_021_)
  );
  sky130_fd_sc_hd__mux2_1 _156_ (
    .A0(o_alu_op_B[0]),
    .A1(i_data_to_read[0]),
    .S(_053_),
    .X(_074_)
  );
  sky130_fd_sc_hd__and2_2 _157_ (
    .A(_092_),
    .B(_074_),
    .X(_022_)
  );
  sky130_fd_sc_hd__mux2_1 _158_ (
    .A0(o_alu_op_B[1]),
    .A1(i_data_to_read[1]),
    .S(_053_),
    .X(_075_)
  );
  sky130_fd_sc_hd__and2_2 _159_ (
    .A(_092_),
    .B(_075_),
    .X(_023_)
  );
  sky130_fd_sc_hd__mux2_1 _160_ (
    .A0(o_alu_op_B[2]),
    .A1(i_data_to_read[2]),
    .S(_053_),
    .X(_076_)
  );
  sky130_fd_sc_hd__and2_2 _161_ (
    .A(_092_),
    .B(_076_),
    .X(_024_)
  );
  sky130_fd_sc_hd__mux2_1 _162_ (
    .A0(o_alu_op_B[3]),
    .A1(i_data_to_read[3]),
    .S(_053_),
    .X(_077_)
  );
  sky130_fd_sc_hd__and2_2 _163_ (
    .A(_092_),
    .B(_077_),
    .X(_025_)
  );
  sky130_fd_sc_hd__mux2_1 _164_ (
    .A0(o_alu_op_B[4]),
    .A1(i_data_to_read[4]),
    .S(_053_),
    .X(_078_)
  );
  sky130_fd_sc_hd__and2_2 _165_ (
    .A(_092_),
    .B(_078_),
    .X(_026_)
  );
  sky130_fd_sc_hd__mux2_1 _166_ (
    .A0(o_alu_op_B[5]),
    .A1(i_data_to_read[5]),
    .S(_053_),
    .X(_079_)
  );
  sky130_fd_sc_hd__and2_2 _167_ (
    .A(_092_),
    .B(_079_),
    .X(_027_)
  );
  sky130_fd_sc_hd__mux2_1 _168_ (
    .A0(o_alu_op_B[6]),
    .A1(i_data_to_read[6]),
    .S(_053_),
    .X(_080_)
  );
  sky130_fd_sc_hd__and2_2 _169_ (
    .A(_092_),
    .B(_080_),
    .X(_028_)
  );
  sky130_fd_sc_hd__mux2_1 _170_ (
    .A0(o_alu_op_B[7]),
    .A1(i_data_to_read[7]),
    .S(_053_),
    .X(_081_)
  );
  sky130_fd_sc_hd__and2_2 _171_ (
    .A(_092_),
    .B(_081_),
    .X(_029_)
  );
  sky130_fd_sc_hd__mux2_1 _172_ (
    .A0(o_data_to_write[0]),
    .A1(i_alu_result[0]),
    .S(_059_),
    .X(_082_)
  );
  sky130_fd_sc_hd__and2_2 _173_ (
    .A(_092_),
    .B(_082_),
    .X(_030_)
  );
  sky130_fd_sc_hd__mux2_1 _174_ (
    .A0(o_data_to_write[1]),
    .A1(i_alu_result[1]),
    .S(_059_),
    .X(_083_)
  );
  sky130_fd_sc_hd__and2_2 _175_ (
    .A(_092_),
    .B(_083_),
    .X(_031_)
  );
  sky130_fd_sc_hd__mux2_1 _176_ (
    .A0(o_data_to_write[2]),
    .A1(i_alu_result[2]),
    .S(_059_),
    .X(_084_)
  );
  sky130_fd_sc_hd__and2_2 _177_ (
    .A(_092_),
    .B(_084_),
    .X(_032_)
  );
  sky130_fd_sc_hd__mux2_1 _178_ (
    .A0(o_data_to_write[3]),
    .A1(i_alu_result[3]),
    .S(_059_),
    .X(_085_)
  );
  sky130_fd_sc_hd__and2_2 _179_ (
    .A(_092_),
    .B(_085_),
    .X(_033_)
  );
  sky130_fd_sc_hd__mux2_1 _180_ (
    .A0(o_data_to_write[4]),
    .A1(i_alu_result[4]),
    .S(_059_),
    .X(_086_)
  );
  sky130_fd_sc_hd__and2_2 _181_ (
    .A(_092_),
    .B(_086_),
    .X(_034_)
  );
  sky130_fd_sc_hd__mux2_1 _182_ (
    .A0(o_data_to_write[5]),
    .A1(i_alu_result[5]),
    .S(_059_),
    .X(_087_)
  );
  sky130_fd_sc_hd__and2_2 _183_ (
    .A(_092_),
    .B(_087_),
    .X(_035_)
  );
  sky130_fd_sc_hd__mux2_1 _184_ (
    .A0(o_data_to_write[6]),
    .A1(i_alu_result[6]),
    .S(_059_),
    .X(_088_)
  );
  sky130_fd_sc_hd__and2_2 _185_ (
    .A(_092_),
    .B(_088_),
    .X(_036_)
  );
  sky130_fd_sc_hd__mux2_1 _186_ (
    .A0(o_data_to_write[7]),
    .A1(i_alu_result[7]),
    .S(_059_),
    .X(_089_)
  );
  sky130_fd_sc_hd__and2_2 _187_ (
    .A(_092_),
    .B(_089_),
    .X(_037_)
  );
  sky130_fd_sc_hd__dfxtp_2 _188_ (
    .CLK(i_clk),
    .D(_000_),
    .Q(\wait_reg[0] )
  );
  sky130_fd_sc_hd__dfxtp_2 _189_ (
    .CLK(i_clk),
    .D(_001_),
    .Q(\wait_reg[1] )
  );
  sky130_fd_sc_hd__dfxtp_2 _190_ (
    .CLK(i_clk),
    .D(_002_),
    .Q(\state[0] )
  );
  sky130_fd_sc_hd__dfxtp_2 _191_ (
    .CLK(i_clk),
    .D(_003_),
    .Q(\state[1] )
  );
  sky130_fd_sc_hd__dfxtp_2 _192_ (
    .CLK(i_clk),
    .D(_004_),
    .Q(\state[2] )
  );
  sky130_fd_sc_hd__dfxtp_2 _193_ (
    .CLK(i_clk),
    .D(_005_),
    .Q(\state[3] )
  );
  sky130_fd_sc_hd__dfxtp_2 _194_ (
    .CLK(i_clk),
    .D(_006_),
    .Q(o_fifo_rx_read)
  );
  sky130_fd_sc_hd__dfxtp_2 _195_ (
    .CLK(i_clk),
    .D(_007_),
    .Q(o_fifo_tx_write)
  );
  sky130_fd_sc_hd__dfxtp_2 _196_ (
    .CLK(i_clk),
    .D(_008_),
    .Q(o_alu_opcode[0])
  );
  sky130_fd_sc_hd__dfxtp_2 _197_ (
    .CLK(i_clk),
    .D(_009_),
    .Q(o_alu_opcode[1])
  );
  sky130_fd_sc_hd__dfxtp_2 _198_ (
    .CLK(i_clk),
    .D(_010_),
    .Q(o_alu_opcode[2])
  );
  sky130_fd_sc_hd__dfxtp_2 _199_ (
    .CLK(i_clk),
    .D(_011_),
    .Q(o_alu_opcode[3])
  );
  sky130_fd_sc_hd__dfxtp_2 _200_ (
    .CLK(i_clk),
    .D(_012_),
    .Q(o_alu_opcode[4])
  );
  sky130_fd_sc_hd__dfxtp_2 _201_ (
    .CLK(i_clk),
    .D(_013_),
    .Q(o_alu_opcode[5])
  );
  sky130_fd_sc_hd__dfxtp_2 _202_ (
    .CLK(i_clk),
    .D(_014_),
    .Q(o_alu_op_A[0])
  );
  sky130_fd_sc_hd__dfxtp_2 _203_ (
    .CLK(i_clk),
    .D(_015_),
    .Q(o_alu_op_A[1])
  );
  sky130_fd_sc_hd__dfxtp_2 _204_ (
    .CLK(i_clk),
    .D(_016_),
    .Q(o_alu_op_A[2])
  );
  sky130_fd_sc_hd__dfxtp_2 _205_ (
    .CLK(i_clk),
    .D(_017_),
    .Q(o_alu_op_A[3])
  );
  sky130_fd_sc_hd__dfxtp_2 _206_ (
    .CLK(i_clk),
    .D(_018_),
    .Q(o_alu_op_A[4])
  );
  sky130_fd_sc_hd__dfxtp_2 _207_ (
    .CLK(i_clk),
    .D(_019_),
    .Q(o_alu_op_A[5])
  );
  sky130_fd_sc_hd__dfxtp_2 _208_ (
    .CLK(i_clk),
    .D(_020_),
    .Q(o_alu_op_A[6])
  );
  sky130_fd_sc_hd__dfxtp_2 _209_ (
    .CLK(i_clk),
    .D(_021_),
    .Q(o_alu_op_A[7])
  );
  sky130_fd_sc_hd__dfxtp_2 _210_ (
    .CLK(i_clk),
    .D(_022_),
    .Q(o_alu_op_B[0])
  );
  sky130_fd_sc_hd__dfxtp_2 _211_ (
    .CLK(i_clk),
    .D(_023_),
    .Q(o_alu_op_B[1])
  );
  sky130_fd_sc_hd__dfxtp_2 _212_ (
    .CLK(i_clk),
    .D(_024_),
    .Q(o_alu_op_B[2])
  );
  sky130_fd_sc_hd__dfxtp_2 _213_ (
    .CLK(i_clk),
    .D(_025_),
    .Q(o_alu_op_B[3])
  );
  sky130_fd_sc_hd__dfxtp_2 _214_ (
    .CLK(i_clk),
    .D(_026_),
    .Q(o_alu_op_B[4])
  );
  sky130_fd_sc_hd__dfxtp_2 _215_ (
    .CLK(i_clk),
    .D(_027_),
    .Q(o_alu_op_B[5])
  );
  sky130_fd_sc_hd__dfxtp_2 _216_ (
    .CLK(i_clk),
    .D(_028_),
    .Q(o_alu_op_B[6])
  );
  sky130_fd_sc_hd__dfxtp_2 _217_ (
    .CLK(i_clk),
    .D(_029_),
    .Q(o_alu_op_B[7])
  );
  sky130_fd_sc_hd__dfxtp_2 _218_ (
    .CLK(i_clk),
    .D(_030_),
    .Q(o_data_to_write[0])
  );
  sky130_fd_sc_hd__dfxtp_2 _219_ (
    .CLK(i_clk),
    .D(_031_),
    .Q(o_data_to_write[1])
  );
  sky130_fd_sc_hd__dfxtp_2 _220_ (
    .CLK(i_clk),
    .D(_032_),
    .Q(o_data_to_write[2])
  );
  sky130_fd_sc_hd__dfxtp_2 _221_ (
    .CLK(i_clk),
    .D(_033_),
    .Q(o_data_to_write[3])
  );
  sky130_fd_sc_hd__dfxtp_2 _222_ (
    .CLK(i_clk),
    .D(_034_),
    .Q(o_data_to_write[4])
  );
  sky130_fd_sc_hd__dfxtp_2 _223_ (
    .CLK(i_clk),
    .D(_035_),
    .Q(o_data_to_write[5])
  );
  sky130_fd_sc_hd__dfxtp_2 _224_ (
    .CLK(i_clk),
    .D(_036_),
    .Q(o_data_to_write[6])
  );
  sky130_fd_sc_hd__dfxtp_2 _225_ (
    .CLK(i_clk),
    .D(_037_),
    .Q(o_data_to_write[7])
  );
endmodule

module \$paramod$6b4111703c44ac05de92b2879f439a7cdf507670\uart_interface (i_clk, i_reset, i_read_uart, i_write_uart, i_rx, i_data_to_write, o_tx_full, o_rx_empty, o_tx, o_data_to_read);
  input i_clk;
  wire i_clk;
  input [7:0] i_data_to_write;
  wire [7:0] i_data_to_write;
  input i_read_uart;
  wire i_read_uart;
  input i_reset;
  wire i_reset;
  input i_rx;
  wire i_rx;
  input i_write_uart;
  wire i_write_uart;
  output [7:0] o_data_to_read;
  wire [7:0] o_data_to_read;
  output o_rx_empty;
  wire o_rx_empty;
  output o_tx;
  wire o_tx;
  output o_tx_full;
  wire o_tx_full;
  wire \rx_data_out[0] ;
  wire \rx_data_out[1] ;
  wire \rx_data_out[2] ;
  wire \rx_data_out[3] ;
  wire \rx_data_out[4] ;
  wire \rx_data_out[5] ;
  wire \rx_data_out[6] ;
  wire \rx_data_out[7] ;
  wire rx_done;
  wire rx_fifo_full_unused;
  wire tick;
  wire tx_done;
  wire tx_empty;
  wire \tx_fifo_out[0] ;
  wire \tx_fifo_out[1] ;
  wire \tx_fifo_out[2] ;
  wire \tx_fifo_out[3] ;
  wire \tx_fifo_out[4] ;
  wire \tx_fifo_out[5] ;
  wire \tx_fifo_out[6] ;
  wire \tx_fifo_out[7] ;
  wire tx_not_empty;
  sky130_fd_sc_hd__inv_2 _0_ (
    .A(tx_empty),
    .Y(tx_not_empty)
  );
  \$paramod$6ec875ae98cdac0db081f5f61c4514b2beea9a0e\baud_rate  baud_rateUnit (
    .i_clk(i_clk),
    .i_reset(i_reset),
    .o_tick(tick)
  );
  \$paramod$a335e5d139a856f4251c37087aeb169656348c98\fifo  fifoRX (
    .i_clk(i_clk),
    .i_data_to_write({ \rx_data_out[7] , \rx_data_out[6] , \rx_data_out[5] , \rx_data_out[4] , \rx_data_out[3] , \rx_data_out[2] , \rx_data_out[1] , \rx_data_out[0]  }),
    .i_read_fifo(i_read_uart),
    .i_reset(i_reset),
    .i_write_fifo(rx_done),
    .o_data_to_read(o_data_to_read),
    .o_fifo_is_empty(o_rx_empty),
    .o_fifo_is_full(rx_fifo_full_unused)
  );
  \$paramod$a335e5d139a856f4251c37087aeb169656348c98\fifo  fifoTX (
    .i_clk(i_clk),
    .i_data_to_write(i_data_to_write),
    .i_read_fifo(tx_done),
    .i_reset(i_reset),
    .i_write_fifo(i_write_uart),
    .o_data_to_read({ \tx_fifo_out[7] , \tx_fifo_out[6] , \tx_fifo_out[5] , \tx_fifo_out[4] , \tx_fifo_out[3] , \tx_fifo_out[2] , \tx_fifo_out[1] , \tx_fifo_out[0]  }),
    .o_fifo_is_empty(tx_empty),
    .o_fifo_is_full(o_tx_full)
  );
  \$paramod$83ab374bc08197efa514ca05ac19072747e23ee5\uart_rx  uartRxUnit (
    .i_clk(i_clk),
    .i_reset(i_reset),
    .i_rx(i_rx),
    .i_tick(tick),
    .o_dout({ \rx_data_out[7] , \rx_data_out[6] , \rx_data_out[5] , \rx_data_out[4] , \rx_data_out[3] , \rx_data_out[2] , \rx_data_out[1] , \rx_data_out[0]  }),
    .o_rx_done(rx_done)
  );
  \$paramod$83ab374bc08197efa514ca05ac19072747e23ee5\uart_tx  uartTxUnit (
    .i_clk(i_clk),
    .i_din({ \tx_fifo_out[7] , \tx_fifo_out[6] , \tx_fifo_out[5] , \tx_fifo_out[4] , \tx_fifo_out[3] , \tx_fifo_out[2] , \tx_fifo_out[1] , \tx_fifo_out[0]  }),
    .i_reset(i_reset),
    .i_tick(tick),
    .i_tx_ready(tx_not_empty),
    .o_tx(o_tx),
    .o_tx_done(tx_done)
  );
endmodule

module \$paramod$6ec875ae98cdac0db081f5f61c4514b2beea9a0e\baud_rate (i_clk, i_reset, o_tick);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire \counter[0] ;
  wire \counter[1] ;
  wire \counter[2] ;
  wire \counter[3] ;
  wire \counter[4] ;
  wire \counter[5] ;
  wire \counter[6] ;
  wire \counter[7] ;
  wire \counter[8] ;
  input i_clk;
  wire i_clk;
  input i_reset;
  wire i_reset;
  output o_tick;
  wire o_tick;
  sky130_fd_sc_hd__inv_2 _30_ (
    .A(\counter[6] ),
    .Y(_09_)
  );
  sky130_fd_sc_hd__inv_2 _31_ (
    .A(\counter[8] ),
    .Y(_10_)
  );
  sky130_fd_sc_hd__inv_2 _32_ (
    .A(i_reset),
    .Y(_11_)
  );
  sky130_fd_sc_hd__nand3b_2 _33_ (
    .A_N(\counter[7] ),
    .B(\counter[6] ),
    .C(\counter[8] ),
    .Y(_12_)
  );
  sky130_fd_sc_hd__nand2b_2 _34_ (
    .A_N(\counter[1] ),
    .B(\counter[0] ),
    .Y(_13_)
  );
  sky130_fd_sc_hd__or4b_2 _35_ (
    .A(\counter[3] ),
    .B(\counter[5] ),
    .C(\counter[4] ),
    .D_N(\counter[2] ),
    .X(_14_)
  );
  sky130_fd_sc_hd__nor3_2 _36_ (
    .A(_12_),
    .B(_13_),
    .C(_14_),
    .Y(o_tick)
  );
  sky130_fd_sc_hd__o31a_2 _37_ (
    .A1(_12_),
    .A2(_13_),
    .A3(_14_),
    .B1(_11_),
    .X(_15_)
  );
  sky130_fd_sc_hd__nor2_2 _38_ (
    .A(\counter[0] ),
    .B(i_reset),
    .Y(_00_)
  );
  sky130_fd_sc_hd__nand2b_2 _39_ (
    .A_N(\counter[0] ),
    .B(\counter[1] ),
    .Y(_16_)
  );
  sky130_fd_sc_hd__a21boi_2 _40_ (
    .A1(_13_),
    .A2(_16_),
    .B1_N(_15_),
    .Y(_01_)
  );
  sky130_fd_sc_hd__nand3_2 _41_ (
    .A(\counter[0] ),
    .B(\counter[1] ),
    .C(\counter[2] ),
    .Y(_17_)
  );
  sky130_fd_sc_hd__a21o_2 _42_ (
    .A1(\counter[0] ),
    .A2(\counter[1] ),
    .B1(\counter[2] ),
    .X(_18_)
  );
  sky130_fd_sc_hd__and3_2 _43_ (
    .A(_15_),
    .B(_17_),
    .C(_18_),
    .X(_02_)
  );
  sky130_fd_sc_hd__and4_2 _44_ (
    .A(\counter[0] ),
    .B(\counter[1] ),
    .C(\counter[3] ),
    .D(\counter[2] ),
    .X(_19_)
  );
  sky130_fd_sc_hd__a31o_2 _45_ (
    .A1(\counter[0] ),
    .A2(\counter[1] ),
    .A3(\counter[2] ),
    .B1(\counter[3] ),
    .X(_20_)
  );
  sky130_fd_sc_hd__and3b_2 _46_ (
    .A_N(_19_),
    .B(_20_),
    .C(_15_),
    .X(_03_)
  );
  sky130_fd_sc_hd__nand2_2 _47_ (
    .A(\counter[4] ),
    .B(_19_),
    .Y(_21_)
  );
  sky130_fd_sc_hd__or2_2 _48_ (
    .A(\counter[4] ),
    .B(_19_),
    .X(_22_)
  );
  sky130_fd_sc_hd__and3_2 _49_ (
    .A(_15_),
    .B(_21_),
    .C(_22_),
    .X(_04_)
  );
  sky130_fd_sc_hd__a21o_2 _50_ (
    .A1(\counter[4] ),
    .A2(_19_),
    .B1(\counter[5] ),
    .X(_23_)
  );
  sky130_fd_sc_hd__and2_2 _51_ (
    .A(\counter[5] ),
    .B(\counter[4] ),
    .X(_24_)
  );
  sky130_fd_sc_hd__nand2_2 _52_ (
    .A(_19_),
    .B(_24_),
    .Y(_25_)
  );
  sky130_fd_sc_hd__and3_2 _53_ (
    .A(_15_),
    .B(_23_),
    .C(_25_),
    .X(_05_)
  );
  sky130_fd_sc_hd__a21o_2 _54_ (
    .A1(_19_),
    .A2(_24_),
    .B1(\counter[6] ),
    .X(_26_)
  );
  sky130_fd_sc_hd__o211a_2 _55_ (
    .A1(_09_),
    .A2(_25_),
    .B1(_26_),
    .C1(_15_),
    .X(_06_)
  );
  sky130_fd_sc_hd__a31o_2 _56_ (
    .A1(\counter[6] ),
    .A2(_19_),
    .A3(_24_),
    .B1(\counter[7] ),
    .X(_27_)
  );
  sky130_fd_sc_hd__nand2_2 _57_ (
    .A(\counter[7] ),
    .B(\counter[6] ),
    .Y(_28_)
  );
  sky130_fd_sc_hd__o211a_2 _58_ (
    .A1(_25_),
    .A2(_28_),
    .B1(_27_),
    .C1(_15_),
    .X(_07_)
  );
  sky130_fd_sc_hd__a41o_2 _59_ (
    .A1(\counter[7] ),
    .A2(\counter[6] ),
    .A3(_19_),
    .A4(_24_),
    .B1(\counter[8] ),
    .X(_29_)
  );
  sky130_fd_sc_hd__o311a_2 _60_ (
    .A1(_10_),
    .A2(_25_),
    .A3(_28_),
    .B1(_29_),
    .C1(_15_),
    .X(_08_)
  );
  sky130_fd_sc_hd__dfxtp_2 _61_ (
    .CLK(i_clk),
    .D(_00_),
    .Q(\counter[0] )
  );
  sky130_fd_sc_hd__dfxtp_2 _62_ (
    .CLK(i_clk),
    .D(_01_),
    .Q(\counter[1] )
  );
  sky130_fd_sc_hd__dfxtp_2 _63_ (
    .CLK(i_clk),
    .D(_02_),
    .Q(\counter[2] )
  );
  sky130_fd_sc_hd__dfxtp_2 _64_ (
    .CLK(i_clk),
    .D(_03_),
    .Q(\counter[3] )
  );
  sky130_fd_sc_hd__dfxtp_2 _65_ (
    .CLK(i_clk),
    .D(_04_),
    .Q(\counter[4] )
  );
  sky130_fd_sc_hd__dfxtp_2 _66_ (
    .CLK(i_clk),
    .D(_05_),
    .Q(\counter[5] )
  );
  sky130_fd_sc_hd__dfxtp_2 _67_ (
    .CLK(i_clk),
    .D(_06_),
    .Q(\counter[6] )
  );
  sky130_fd_sc_hd__dfxtp_2 _68_ (
    .CLK(i_clk),
    .D(_07_),
    .Q(\counter[7] )
  );
  sky130_fd_sc_hd__dfxtp_2 _69_ (
    .CLK(i_clk),
    .D(_08_),
    .Q(\counter[8] )
  );
endmodule

module \$paramod$83ab374bc08197efa514ca05ac19072747e23ee5\uart_rx (i_clk, i_reset, i_rx, i_tick, o_rx_done, o_dout);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  input i_clk;
  wire i_clk;
  input i_reset;
  wire i_reset;
  input i_rx;
  wire i_rx;
  input i_tick;
  wire i_tick;
  wire \n[0] ;
  wire \n[1] ;
  wire \n[2] ;
  output [7:0] o_dout;
  wire [7:0] o_dout;
  output o_rx_done;
  wire o_rx_done;
  wire \s[0] ;
  wire \s[1] ;
  wire \s[2] ;
  wire \s[3] ;
  wire \state[0] ;
  wire \state[1] ;
  wire \state[2] ;
  wire \state[3] ;
  sky130_fd_sc_hd__inv_2 _068_ (
    .A(i_rx),
    .Y(_025_)
  );
  sky130_fd_sc_hd__inv_2 _069_ (
    .A(\n[2] ),
    .Y(_026_)
  );
  sky130_fd_sc_hd__inv_2 _070_ (
    .A(\s[0] ),
    .Y(_027_)
  );
  sky130_fd_sc_hd__inv_2 _071_ (
    .A(i_reset),
    .Y(_028_)
  );
  sky130_fd_sc_hd__inv_2 _072_ (
    .A(i_tick),
    .Y(_029_)
  );
  sky130_fd_sc_hd__inv_2 _073_ (
    .A(\state[1] ),
    .Y(_030_)
  );
  sky130_fd_sc_hd__inv_2 _074_ (
    .A(\state[2] ),
    .Y(_031_)
  );
  sky130_fd_sc_hd__and2_2 _075_ (
    .A(\s[1] ),
    .B(\s[0] ),
    .X(_032_)
  );
  sky130_fd_sc_hd__and3_2 _076_ (
    .A(\s[2] ),
    .B(\s[1] ),
    .C(\s[0] ),
    .X(_033_)
  );
  sky130_fd_sc_hd__and4_2 _077_ (
    .A(\s[3] ),
    .B(\s[2] ),
    .C(\s[1] ),
    .D(\s[0] ),
    .X(_034_)
  );
  sky130_fd_sc_hd__nand2_2 _078_ (
    .A(\s[3] ),
    .B(_033_),
    .Y(_035_)
  );
  sky130_fd_sc_hd__a21o_2 _079_ (
    .A1(i_tick),
    .A2(_034_),
    .B1(\state[3] ),
    .X(_036_)
  );
  sky130_fd_sc_hd__nand3_2 _080_ (
    .A(\n[2] ),
    .B(\n[1] ),
    .C(\n[0] ),
    .Y(_037_)
  );
  sky130_fd_sc_hd__nor2_2 _081_ (
    .A(_030_),
    .B(_037_),
    .Y(_038_)
  );
  sky130_fd_sc_hd__o311a_2 _082_ (
    .A1(_029_),
    .A2(_035_),
    .A3(_038_),
    .B1(_036_),
    .C1(_028_),
    .X(_003_)
  );
  sky130_fd_sc_hd__nand4b_2 _083_ (
    .A_N(\s[3] ),
    .B(\s[2] ),
    .C(\s[1] ),
    .D(\s[0] ),
    .Y(_039_)
  );
  sky130_fd_sc_hd__and2b_2 _084_ (
    .A_N(i_tick),
    .B(\state[2] ),
    .X(_040_)
  );
  sky130_fd_sc_hd__a221o_2 _085_ (
    .A1(_025_),
    .A2(\state[0] ),
    .B1(_039_),
    .B2(\state[2] ),
    .C1(_040_),
    .X(_041_)
  );
  sky130_fd_sc_hd__and2_2 _086_ (
    .A(_028_),
    .B(_041_),
    .X(_002_)
  );
  sky130_fd_sc_hd__a21oi_2 _087_ (
    .A1(i_tick),
    .A2(_034_),
    .B1(_030_),
    .Y(_042_)
  );
  sky130_fd_sc_hd__a2bb2o_2 _088_ (
    .A1_N(_031_),
    .A2_N(_039_),
    .B1(_037_),
    .B2(\state[1] ),
    .X(_043_)
  );
  sky130_fd_sc_hd__a21oi_2 _089_ (
    .A1(i_tick),
    .A2(_043_),
    .B1(_042_),
    .Y(_044_)
  );
  sky130_fd_sc_hd__nor2_2 _090_ (
    .A(i_reset),
    .B(_044_),
    .Y(_001_)
  );
  sky130_fd_sc_hd__and3_2 _091_ (
    .A(\state[3] ),
    .B(i_tick),
    .C(_034_),
    .X(_045_)
  );
  sky130_fd_sc_hd__a211o_2 _092_ (
    .A1(i_rx),
    .A2(\state[0] ),
    .B1(_045_),
    .C1(i_reset),
    .X(_000_)
  );
  sky130_fd_sc_hd__and2_2 _093_ (
    .A(i_rx),
    .B(_045_),
    .X(o_rx_done)
  );
  sky130_fd_sc_hd__o21a_2 _094_ (
    .A1(_029_),
    .A2(_034_),
    .B1(\state[3] ),
    .X(_046_)
  );
  sky130_fd_sc_hd__a221o_2 _095_ (
    .A1(_029_),
    .A2(\state[1] ),
    .B1(\state[0] ),
    .B2(i_rx),
    .C1(_040_),
    .X(_047_)
  );
  sky130_fd_sc_hd__nor3_2 _096_ (
    .A(\state[3] ),
    .B(\state[1] ),
    .C(\state[2] ),
    .Y(_048_)
  );
  sky130_fd_sc_hd__o31ai_2 _097_ (
    .A1(_046_),
    .A2(_047_),
    .A3(_048_),
    .B1(_027_),
    .Y(_049_)
  );
  sky130_fd_sc_hd__o311a_2 _098_ (
    .A1(_027_),
    .A2(_046_),
    .A3(_047_),
    .B1(_049_),
    .C1(_028_),
    .X(_004_)
  );
  sky130_fd_sc_hd__o21a_2 _099_ (
    .A1(_046_),
    .A2(_047_),
    .B1(\s[1] ),
    .X(_050_)
  );
  sky130_fd_sc_hd__nor4_2 _100_ (
    .A(_032_),
    .B(_046_),
    .C(_047_),
    .D(_048_),
    .Y(_051_)
  );
  sky130_fd_sc_hd__o221a_2 _101_ (
    .A1(\s[1] ),
    .A2(\s[0] ),
    .B1(_050_),
    .B2(_051_),
    .C1(_028_),
    .X(_005_)
  );
  sky130_fd_sc_hd__o21a_2 _102_ (
    .A1(_046_),
    .A2(_047_),
    .B1(\s[2] ),
    .X(_052_)
  );
  sky130_fd_sc_hd__nor4_2 _103_ (
    .A(_033_),
    .B(_046_),
    .C(_047_),
    .D(_048_),
    .Y(_053_)
  );
  sky130_fd_sc_hd__o221a_2 _104_ (
    .A1(\s[2] ),
    .A2(_032_),
    .B1(_052_),
    .B2(_053_),
    .C1(_028_),
    .X(_006_)
  );
  sky130_fd_sc_hd__nor3b_2 _105_ (
    .A(_046_),
    .B(_047_),
    .C_N(_033_),
    .Y(_054_)
  );
  sky130_fd_sc_hd__a211o_2 _106_ (
    .A1(\state[2] ),
    .A2(_039_),
    .B1(\state[3] ),
    .C1(\state[1] ),
    .X(_055_)
  );
  sky130_fd_sc_hd__a211o_2 _107_ (
    .A1(_035_),
    .A2(_055_),
    .B1(_047_),
    .C1(_046_),
    .X(_056_)
  );
  sky130_fd_sc_hd__o211a_2 _108_ (
    .A1(\s[3] ),
    .A2(_054_),
    .B1(_056_),
    .C1(_028_),
    .X(_007_)
  );
  sky130_fd_sc_hd__or3_2 _109_ (
    .A(\state[3] ),
    .B(\state[2] ),
    .C(\state[0] ),
    .X(_057_)
  );
  sky130_fd_sc_hd__a2111oi_2 _110_ (
    .A1(\state[2] ),
    .A2(_039_),
    .B1(_040_),
    .C1(\state[0] ),
    .D1(\state[3] ),
    .Y(_058_)
  );
  sky130_fd_sc_hd__a21oi_2 _111_ (
    .A1(_030_),
    .A2(_058_),
    .B1(i_reset),
    .Y(_059_)
  );
  sky130_fd_sc_hd__a31o_2 _112_ (
    .A1(i_tick),
    .A2(_034_),
    .A3(_037_),
    .B1(_030_),
    .X(_060_)
  );
  sky130_fd_sc_hd__nand3_2 _113_ (
    .A(\n[0] ),
    .B(_058_),
    .C(_060_),
    .Y(_061_)
  );
  sky130_fd_sc_hd__a31o_2 _114_ (
    .A1(\state[1] ),
    .A2(_058_),
    .A3(_060_),
    .B1(\n[0] ),
    .X(_062_)
  );
  sky130_fd_sc_hd__and3_2 _115_ (
    .A(_028_),
    .B(_061_),
    .C(_062_),
    .X(_008_)
  );
  sky130_fd_sc_hd__nand4_2 _116_ (
    .A(\n[1] ),
    .B(\n[0] ),
    .C(_058_),
    .D(_060_),
    .Y(_063_)
  );
  sky130_fd_sc_hd__a31o_2 _117_ (
    .A1(\n[0] ),
    .A2(_058_),
    .A3(_060_),
    .B1(\n[1] ),
    .X(_064_)
  );
  sky130_fd_sc_hd__and3_2 _118_ (
    .A(_059_),
    .B(_063_),
    .C(_064_),
    .X(_009_)
  );
  sky130_fd_sc_hd__a21boi_2 _119_ (
    .A1(_026_),
    .A2(_063_),
    .B1_N(_059_),
    .Y(_010_)
  );
  sky130_fd_sc_hd__nor2_2 _120_ (
    .A(_042_),
    .B(_057_),
    .Y(_065_)
  );
  sky130_fd_sc_hd__or3_2 _121_ (
    .A(o_dout[1]),
    .B(_042_),
    .C(_057_),
    .X(_066_)
  );
  sky130_fd_sc_hd__o211a_2 _122_ (
    .A1(o_dout[0]),
    .A2(_065_),
    .B1(_066_),
    .C1(_028_),
    .X(_011_)
  );
  sky130_fd_sc_hd__or3_2 _123_ (
    .A(o_dout[2]),
    .B(_042_),
    .C(_057_),
    .X(_067_)
  );
  sky130_fd_sc_hd__o211a_2 _124_ (
    .A1(o_dout[1]),
    .A2(_065_),
    .B1(_067_),
    .C1(_028_),
    .X(_012_)
  );
  sky130_fd_sc_hd__or3_2 _125_ (
    .A(o_dout[3]),
    .B(_042_),
    .C(_057_),
    .X(_019_)
  );
  sky130_fd_sc_hd__o211a_2 _126_ (
    .A1(o_dout[2]),
    .A2(_065_),
    .B1(_019_),
    .C1(_028_),
    .X(_013_)
  );
  sky130_fd_sc_hd__or3_2 _127_ (
    .A(o_dout[4]),
    .B(_042_),
    .C(_057_),
    .X(_020_)
  );
  sky130_fd_sc_hd__o211a_2 _128_ (
    .A1(o_dout[3]),
    .A2(_065_),
    .B1(_020_),
    .C1(_028_),
    .X(_014_)
  );
  sky130_fd_sc_hd__or3_2 _129_ (
    .A(o_dout[5]),
    .B(_042_),
    .C(_057_),
    .X(_021_)
  );
  sky130_fd_sc_hd__o211a_2 _130_ (
    .A1(o_dout[4]),
    .A2(_065_),
    .B1(_021_),
    .C1(_028_),
    .X(_015_)
  );
  sky130_fd_sc_hd__or3_2 _131_ (
    .A(o_dout[6]),
    .B(_042_),
    .C(_057_),
    .X(_022_)
  );
  sky130_fd_sc_hd__o211a_2 _132_ (
    .A1(o_dout[5]),
    .A2(_065_),
    .B1(_022_),
    .C1(_028_),
    .X(_016_)
  );
  sky130_fd_sc_hd__or3_2 _133_ (
    .A(o_dout[7]),
    .B(_042_),
    .C(_057_),
    .X(_023_)
  );
  sky130_fd_sc_hd__o211a_2 _134_ (
    .A1(o_dout[6]),
    .A2(_065_),
    .B1(_023_),
    .C1(_028_),
    .X(_017_)
  );
  sky130_fd_sc_hd__or3_2 _135_ (
    .A(i_rx),
    .B(_042_),
    .C(_057_),
    .X(_024_)
  );
  sky130_fd_sc_hd__o211a_2 _136_ (
    .A1(o_dout[7]),
    .A2(_065_),
    .B1(_024_),
    .C1(_028_),
    .X(_018_)
  );
  sky130_fd_sc_hd__dfxtp_2 _137_ (
    .CLK(i_clk),
    .D(_000_),
    .Q(\state[0] )
  );
  sky130_fd_sc_hd__dfxtp_2 _138_ (
    .CLK(i_clk),
    .D(_001_),
    .Q(\state[1] )
  );
  sky130_fd_sc_hd__dfxtp_2 _139_ (
    .CLK(i_clk),
    .D(_002_),
    .Q(\state[2] )
  );
  sky130_fd_sc_hd__dfxtp_2 _140_ (
    .CLK(i_clk),
    .D(_003_),
    .Q(\state[3] )
  );
  sky130_fd_sc_hd__dfxtp_2 _141_ (
    .CLK(i_clk),
    .D(_004_),
    .Q(\s[0] )
  );
  sky130_fd_sc_hd__dfxtp_2 _142_ (
    .CLK(i_clk),
    .D(_005_),
    .Q(\s[1] )
  );
  sky130_fd_sc_hd__dfxtp_2 _143_ (
    .CLK(i_clk),
    .D(_006_),
    .Q(\s[2] )
  );
  sky130_fd_sc_hd__dfxtp_2 _144_ (
    .CLK(i_clk),
    .D(_007_),
    .Q(\s[3] )
  );
  sky130_fd_sc_hd__dfxtp_2 _145_ (
    .CLK(i_clk),
    .D(_008_),
    .Q(\n[0] )
  );
  sky130_fd_sc_hd__dfxtp_2 _146_ (
    .CLK(i_clk),
    .D(_009_),
    .Q(\n[1] )
  );
  sky130_fd_sc_hd__dfxtp_2 _147_ (
    .CLK(i_clk),
    .D(_010_),
    .Q(\n[2] )
  );
  sky130_fd_sc_hd__dfxtp_2 _148_ (
    .CLK(i_clk),
    .D(_011_),
    .Q(o_dout[0])
  );
  sky130_fd_sc_hd__dfxtp_2 _149_ (
    .CLK(i_clk),
    .D(_012_),
    .Q(o_dout[1])
  );
  sky130_fd_sc_hd__dfxtp_2 _150_ (
    .CLK(i_clk),
    .D(_013_),
    .Q(o_dout[2])
  );
  sky130_fd_sc_hd__dfxtp_2 _151_ (
    .CLK(i_clk),
    .D(_014_),
    .Q(o_dout[3])
  );
  sky130_fd_sc_hd__dfxtp_2 _152_ (
    .CLK(i_clk),
    .D(_015_),
    .Q(o_dout[4])
  );
  sky130_fd_sc_hd__dfxtp_2 _153_ (
    .CLK(i_clk),
    .D(_016_),
    .Q(o_dout[5])
  );
  sky130_fd_sc_hd__dfxtp_2 _154_ (
    .CLK(i_clk),
    .D(_017_),
    .Q(o_dout[6])
  );
  sky130_fd_sc_hd__dfxtp_2 _155_ (
    .CLK(i_clk),
    .D(_018_),
    .Q(o_dout[7])
  );
endmodule

module \$paramod$83ab374bc08197efa514ca05ac19072747e23ee5\uart_tx (i_clk, i_reset, i_tx_ready, i_tick, i_din, o_tx_done, o_tx);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  input i_clk;
  wire i_clk;
  input [7:0] i_din;
  wire [7:0] i_din;
  input i_reset;
  wire i_reset;
  input i_tick;
  wire i_tick;
  input i_tx_ready;
  wire i_tx_ready;
  wire \n[0] ;
  wire \n[1] ;
  wire \n[2] ;
  output o_tx;
  wire o_tx;
  output o_tx_done;
  wire o_tx_done;
  wire \s[0] ;
  wire \s[1] ;
  wire \s[2] ;
  wire \s[3] ;
  wire \send_byte[0] ;
  wire \send_byte[1] ;
  wire \send_byte[2] ;
  wire \send_byte[3] ;
  wire \send_byte[4] ;
  wire \send_byte[5] ;
  wire \send_byte[6] ;
  wire \send_byte[7] ;
  wire \state[0] ;
  wire \state[1] ;
  wire \state[2] ;
  wire \state[3] ;
  sky130_fd_sc_hd__inv_2 _077_ (
    .A(\s[0] ),
    .Y(_039_)
  );
  sky130_fd_sc_hd__inv_2 _078_ (
    .A(\state[1] ),
    .Y(_040_)
  );
  sky130_fd_sc_hd__inv_2 _079_ (
    .A(i_tick),
    .Y(_041_)
  );
  sky130_fd_sc_hd__inv_2 _080_ (
    .A(i_tx_ready),
    .Y(_042_)
  );
  sky130_fd_sc_hd__inv_2 _081_ (
    .A(i_reset),
    .Y(_043_)
  );
  sky130_fd_sc_hd__and4_2 _082_ (
    .A(\s[3] ),
    .B(\s[2] ),
    .C(\s[1] ),
    .D(\s[0] ),
    .X(_044_)
  );
  sky130_fd_sc_hd__and2_2 _083_ (
    .A(i_tick),
    .B(_044_),
    .X(_045_)
  );
  sky130_fd_sc_hd__nand2_2 _084_ (
    .A(i_tick),
    .B(_044_),
    .Y(_046_)
  );
  sky130_fd_sc_hd__and3_2 _085_ (
    .A(i_tick),
    .B(\state[3] ),
    .C(_044_),
    .X(o_tx_done)
  );
  sky130_fd_sc_hd__a32o_2 _086_ (
    .A1(i_tick),
    .A2(\state[3] ),
    .A3(_044_),
    .B1(_042_),
    .B2(\state[0] ),
    .X(_047_)
  );
  sky130_fd_sc_hd__or2_2 _087_ (
    .A(i_reset),
    .B(_047_),
    .X(_000_)
  );
  sky130_fd_sc_hd__nand2_2 _088_ (
    .A(\n[1] ),
    .B(\n[0] ),
    .Y(_048_)
  );
  sky130_fd_sc_hd__and3_2 _089_ (
    .A(\n[2] ),
    .B(\n[1] ),
    .C(\n[0] ),
    .X(_049_)
  );
  sky130_fd_sc_hd__nand3_2 _090_ (
    .A(\n[2] ),
    .B(\n[1] ),
    .C(\n[0] ),
    .Y(_050_)
  );
  sky130_fd_sc_hd__a31o_2 _091_ (
    .A1(i_tick),
    .A2(_044_),
    .A3(_049_),
    .B1(_040_),
    .X(_051_)
  );
  sky130_fd_sc_hd__nand2_2 _092_ (
    .A(\state[2] ),
    .B(_045_),
    .Y(_052_)
  );
  sky130_fd_sc_hd__a21oi_2 _093_ (
    .A1(_051_),
    .A2(_052_),
    .B1(i_reset),
    .Y(_001_)
  );
  sky130_fd_sc_hd__a22o_2 _094_ (
    .A1(i_tx_ready),
    .A2(\state[0] ),
    .B1(_046_),
    .B2(\state[2] ),
    .X(_053_)
  );
  sky130_fd_sc_hd__and2_2 _095_ (
    .A(_043_),
    .B(_053_),
    .X(_002_)
  );
  sky130_fd_sc_hd__and4_2 _096_ (
    .A(\state[1] ),
    .B(i_tick),
    .C(_044_),
    .D(_049_),
    .X(_054_)
  );
  sky130_fd_sc_hd__a21oi_2 _097_ (
    .A1(\state[3] ),
    .A2(_046_),
    .B1(_054_),
    .Y(_055_)
  );
  sky130_fd_sc_hd__nor2_2 _098_ (
    .A(i_reset),
    .B(_055_),
    .Y(_003_)
  );
  sky130_fd_sc_hd__nor2_2 _099_ (
    .A(\state[2] ),
    .B(\state[3] ),
    .Y(_056_)
  );
  sky130_fd_sc_hd__nor3_2 _100_ (
    .A(\state[2] ),
    .B(\state[1] ),
    .C(\state[3] ),
    .Y(_057_)
  );
  sky130_fd_sc_hd__nor2_2 _101_ (
    .A(i_tick),
    .B(_057_),
    .Y(_058_)
  );
  sky130_fd_sc_hd__o31ai_2 _102_ (
    .A1(_041_),
    .A2(_047_),
    .A3(_057_),
    .B1(_039_),
    .Y(_059_)
  );
  sky130_fd_sc_hd__o311a_2 _103_ (
    .A1(_039_),
    .A2(_047_),
    .A3(_058_),
    .B1(_059_),
    .C1(_043_),
    .X(_004_)
  );
  sky130_fd_sc_hd__o21a_2 _104_ (
    .A1(_047_),
    .A2(_058_),
    .B1(\s[1] ),
    .X(_060_)
  );
  sky130_fd_sc_hd__a2111oi_2 _105_ (
    .A1(\s[1] ),
    .A2(\s[0] ),
    .B1(_041_),
    .C1(_047_),
    .D1(_057_),
    .Y(_061_)
  );
  sky130_fd_sc_hd__o221a_2 _106_ (
    .A1(\s[1] ),
    .A2(\s[0] ),
    .B1(_060_),
    .B2(_061_),
    .C1(_043_),
    .X(_005_)
  );
  sky130_fd_sc_hd__o21ai_2 _107_ (
    .A1(_047_),
    .A2(_058_),
    .B1(\s[2] ),
    .Y(_062_)
  );
  sky130_fd_sc_hd__and3_2 _108_ (
    .A(\s[2] ),
    .B(\s[1] ),
    .C(\s[0] ),
    .X(_063_)
  );
  sky130_fd_sc_hd__or4_2 _109_ (
    .A(_041_),
    .B(_047_),
    .C(_057_),
    .D(_063_),
    .X(_064_)
  );
  sky130_fd_sc_hd__a21oi_2 _110_ (
    .A1(\s[1] ),
    .A2(\s[0] ),
    .B1(\s[2] ),
    .Y(_065_)
  );
  sky130_fd_sc_hd__a211oi_2 _111_ (
    .A1(_062_),
    .A2(_064_),
    .B1(_065_),
    .C1(i_reset),
    .Y(_006_)
  );
  sky130_fd_sc_hd__o21ai_2 _112_ (
    .A1(_047_),
    .A2(_058_),
    .B1(\s[3] ),
    .Y(_066_)
  );
  sky130_fd_sc_hd__or4_2 _113_ (
    .A(_041_),
    .B(_044_),
    .C(_047_),
    .D(_057_),
    .X(_067_)
  );
  sky130_fd_sc_hd__nor2_2 _114_ (
    .A(\s[3] ),
    .B(_063_),
    .Y(_068_)
  );
  sky130_fd_sc_hd__a211oi_2 _115_ (
    .A1(_066_),
    .A2(_067_),
    .B1(_068_),
    .C1(i_reset),
    .Y(_007_)
  );
  sky130_fd_sc_hd__o2bb2a_2 _116_ (
    .A1_N(i_tick),
    .A2_N(_044_),
    .B1(\state[2] ),
    .B2(\state[1] ),
    .X(_069_)
  );
  sky130_fd_sc_hd__nor2_2 _117_ (
    .A(\state[0] ),
    .B(\state[3] ),
    .Y(_070_)
  );
  sky130_fd_sc_hd__or2_2 _118_ (
    .A(\state[0] ),
    .B(\state[3] ),
    .X(_071_)
  );
  sky130_fd_sc_hd__a31o_2 _119_ (
    .A1(\state[1] ),
    .A2(_045_),
    .A3(_070_),
    .B1(\n[0] ),
    .X(_072_)
  );
  sky130_fd_sc_hd__or4b_2 _120_ (
    .A(_054_),
    .B(_069_),
    .C(_071_),
    .D_N(\n[0] ),
    .X(_073_)
  );
  sky130_fd_sc_hd__and3_2 _121_ (
    .A(_043_),
    .B(_072_),
    .C(_073_),
    .X(_008_)
  );
  sky130_fd_sc_hd__nor4_2 _122_ (
    .A(_048_),
    .B(_054_),
    .C(_069_),
    .D(_071_),
    .Y(_074_)
  );
  sky130_fd_sc_hd__o31a_2 _123_ (
    .A1(_054_),
    .A2(_069_),
    .A3(_071_),
    .B1(\n[1] ),
    .X(_075_)
  );
  sky130_fd_sc_hd__or2_2 _124_ (
    .A(\n[1] ),
    .B(\n[0] ),
    .X(_076_)
  );
  sky130_fd_sc_hd__and4_2 _125_ (
    .A(\state[1] ),
    .B(_045_),
    .C(_048_),
    .D(_070_),
    .X(_020_)
  );
  sky130_fd_sc_hd__o211a_2 _126_ (
    .A1(_075_),
    .A2(_020_),
    .B1(_076_),
    .C1(_043_),
    .X(_009_)
  );
  sky130_fd_sc_hd__a2111o_2 _127_ (
    .A1(\state[1] ),
    .A2(_050_),
    .B1(_054_),
    .C1(_069_),
    .D1(_071_),
    .X(_021_)
  );
  sky130_fd_sc_hd__o211a_2 _128_ (
    .A1(\n[2] ),
    .A2(_074_),
    .B1(_021_),
    .C1(_043_),
    .X(_010_)
  );
  sky130_fd_sc_hd__o31ai_2 _129_ (
    .A1(_040_),
    .A2(_041_),
    .A3(_044_),
    .B1(_056_),
    .Y(_022_)
  );
  sky130_fd_sc_hd__nor3_2 _130_ (
    .A(_047_),
    .B(_058_),
    .C(_022_),
    .Y(_023_)
  );
  sky130_fd_sc_hd__mux2_1 _131_ (
    .A0(i_din[0]),
    .A1(\send_byte[1] ),
    .S(\state[1] ),
    .X(_024_)
  );
  sky130_fd_sc_hd__or4_2 _132_ (
    .A(_047_),
    .B(_058_),
    .C(_022_),
    .D(_024_),
    .X(_025_)
  );
  sky130_fd_sc_hd__o211a_2 _133_ (
    .A1(\send_byte[0] ),
    .A2(_023_),
    .B1(_025_),
    .C1(_043_),
    .X(_011_)
  );
  sky130_fd_sc_hd__mux2_1 _134_ (
    .A0(i_din[1]),
    .A1(\send_byte[2] ),
    .S(\state[1] ),
    .X(_026_)
  );
  sky130_fd_sc_hd__or4_2 _135_ (
    .A(_047_),
    .B(_058_),
    .C(_022_),
    .D(_026_),
    .X(_027_)
  );
  sky130_fd_sc_hd__o211a_2 _136_ (
    .A1(\send_byte[1] ),
    .A2(_023_),
    .B1(_027_),
    .C1(_043_),
    .X(_012_)
  );
  sky130_fd_sc_hd__mux2_1 _137_ (
    .A0(i_din[2]),
    .A1(\send_byte[3] ),
    .S(\state[1] ),
    .X(_028_)
  );
  sky130_fd_sc_hd__or4_2 _138_ (
    .A(_047_),
    .B(_058_),
    .C(_022_),
    .D(_028_),
    .X(_029_)
  );
  sky130_fd_sc_hd__o211a_2 _139_ (
    .A1(\send_byte[2] ),
    .A2(_023_),
    .B1(_029_),
    .C1(_043_),
    .X(_013_)
  );
  sky130_fd_sc_hd__mux2_1 _140_ (
    .A0(i_din[3]),
    .A1(\send_byte[4] ),
    .S(\state[1] ),
    .X(_030_)
  );
  sky130_fd_sc_hd__or4_2 _141_ (
    .A(_047_),
    .B(_058_),
    .C(_022_),
    .D(_030_),
    .X(_031_)
  );
  sky130_fd_sc_hd__o211a_2 _142_ (
    .A1(\send_byte[3] ),
    .A2(_023_),
    .B1(_031_),
    .C1(_043_),
    .X(_014_)
  );
  sky130_fd_sc_hd__mux2_1 _143_ (
    .A0(i_din[4]),
    .A1(\send_byte[5] ),
    .S(\state[1] ),
    .X(_032_)
  );
  sky130_fd_sc_hd__or4_2 _144_ (
    .A(_047_),
    .B(_058_),
    .C(_022_),
    .D(_032_),
    .X(_033_)
  );
  sky130_fd_sc_hd__o211a_2 _145_ (
    .A1(\send_byte[4] ),
    .A2(_023_),
    .B1(_033_),
    .C1(_043_),
    .X(_015_)
  );
  sky130_fd_sc_hd__mux2_1 _146_ (
    .A0(i_din[5]),
    .A1(\send_byte[6] ),
    .S(\state[1] ),
    .X(_034_)
  );
  sky130_fd_sc_hd__or4_2 _147_ (
    .A(_047_),
    .B(_058_),
    .C(_022_),
    .D(_034_),
    .X(_035_)
  );
  sky130_fd_sc_hd__o211a_2 _148_ (
    .A1(\send_byte[5] ),
    .A2(_023_),
    .B1(_035_),
    .C1(_043_),
    .X(_016_)
  );
  sky130_fd_sc_hd__mux2_1 _149_ (
    .A0(i_din[6]),
    .A1(\send_byte[7] ),
    .S(\state[1] ),
    .X(_036_)
  );
  sky130_fd_sc_hd__or4_2 _150_ (
    .A(_047_),
    .B(_058_),
    .C(_022_),
    .D(_036_),
    .X(_037_)
  );
  sky130_fd_sc_hd__o211a_2 _151_ (
    .A1(\send_byte[6] ),
    .A2(_023_),
    .B1(_037_),
    .C1(_043_),
    .X(_017_)
  );
  sky130_fd_sc_hd__a2111o_2 _152_ (
    .A1(_040_),
    .A2(i_din[7]),
    .B1(_047_),
    .C1(_058_),
    .D1(_022_),
    .X(_038_)
  );
  sky130_fd_sc_hd__o211a_2 _153_ (
    .A1(\send_byte[7] ),
    .A2(_023_),
    .B1(_038_),
    .C1(_043_),
    .X(_018_)
  );
  sky130_fd_sc_hd__a211o_2 _154_ (
    .A1(\send_byte[0] ),
    .A2(\state[1] ),
    .B1(i_reset),
    .C1(_071_),
    .X(_019_)
  );
  sky130_fd_sc_hd__dfxtp_2 _155_ (
    .CLK(i_clk),
    .D(_000_),
    .Q(\state[0] )
  );
  sky130_fd_sc_hd__dfxtp_2 _156_ (
    .CLK(i_clk),
    .D(_001_),
    .Q(\state[1] )
  );
  sky130_fd_sc_hd__dfxtp_2 _157_ (
    .CLK(i_clk),
    .D(_002_),
    .Q(\state[2] )
  );
  sky130_fd_sc_hd__dfxtp_2 _158_ (
    .CLK(i_clk),
    .D(_003_),
    .Q(\state[3] )
  );
  sky130_fd_sc_hd__dfxtp_2 _159_ (
    .CLK(i_clk),
    .D(_004_),
    .Q(\s[0] )
  );
  sky130_fd_sc_hd__dfxtp_2 _160_ (
    .CLK(i_clk),
    .D(_005_),
    .Q(\s[1] )
  );
  sky130_fd_sc_hd__dfxtp_2 _161_ (
    .CLK(i_clk),
    .D(_006_),
    .Q(\s[2] )
  );
  sky130_fd_sc_hd__dfxtp_2 _162_ (
    .CLK(i_clk),
    .D(_007_),
    .Q(\s[3] )
  );
  sky130_fd_sc_hd__dfxtp_2 _163_ (
    .CLK(i_clk),
    .D(_008_),
    .Q(\n[0] )
  );
  sky130_fd_sc_hd__dfxtp_2 _164_ (
    .CLK(i_clk),
    .D(_009_),
    .Q(\n[1] )
  );
  sky130_fd_sc_hd__dfxtp_2 _165_ (
    .CLK(i_clk),
    .D(_010_),
    .Q(\n[2] )
  );
  sky130_fd_sc_hd__dfxtp_2 _166_ (
    .CLK(i_clk),
    .D(_011_),
    .Q(\send_byte[0] )
  );
  sky130_fd_sc_hd__dfxtp_2 _167_ (
    .CLK(i_clk),
    .D(_012_),
    .Q(\send_byte[1] )
  );
  sky130_fd_sc_hd__dfxtp_2 _168_ (
    .CLK(i_clk),
    .D(_013_),
    .Q(\send_byte[2] )
  );
  sky130_fd_sc_hd__dfxtp_2 _169_ (
    .CLK(i_clk),
    .D(_014_),
    .Q(\send_byte[3] )
  );
  sky130_fd_sc_hd__dfxtp_2 _170_ (
    .CLK(i_clk),
    .D(_015_),
    .Q(\send_byte[4] )
  );
  sky130_fd_sc_hd__dfxtp_2 _171_ (
    .CLK(i_clk),
    .D(_016_),
    .Q(\send_byte[5] )
  );
  sky130_fd_sc_hd__dfxtp_2 _172_ (
    .CLK(i_clk),
    .D(_017_),
    .Q(\send_byte[6] )
  );
  sky130_fd_sc_hd__dfxtp_2 _173_ (
    .CLK(i_clk),
    .D(_018_),
    .Q(\send_byte[7] )
  );
  sky130_fd_sc_hd__dfxtp_2 _174_ (
    .CLK(i_clk),
    .D(_019_),
    .Q(o_tx)
  );
endmodule

module \$paramod$a335e5d139a856f4251c37087aeb169656348c98\fifo (i_clk, i_reset, i_read_fifo, i_write_fifo, i_data_to_write, o_fifo_is_empty, o_fifo_is_full, o_data_to_read);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire \array[0][0] ;
  wire \array[0][1] ;
  wire \array[0][2] ;
  wire \array[0][3] ;
  wire \array[0][4] ;
  wire \array[0][5] ;
  wire \array[0][6] ;
  wire \array[0][7] ;
  wire \array[1][0] ;
  wire \array[1][1] ;
  wire \array[1][2] ;
  wire \array[1][3] ;
  wire \array[1][4] ;
  wire \array[1][5] ;
  wire \array[1][6] ;
  wire \array[1][7] ;
  wire \array[2][0] ;
  wire \array[2][1] ;
  wire \array[2][2] ;
  wire \array[2][3] ;
  wire \array[2][4] ;
  wire \array[2][5] ;
  wire \array[2][6] ;
  wire \array[2][7] ;
  wire \array[3][0] ;
  wire \array[3][1] ;
  wire \array[3][2] ;
  wire \array[3][3] ;
  wire \array[3][4] ;
  wire \array[3][5] ;
  wire \array[3][6] ;
  wire \array[3][7] ;
  input i_clk;
  wire i_clk;
  input [7:0] i_data_to_write;
  wire [7:0] i_data_to_write;
  input i_read_fifo;
  wire i_read_fifo;
  input i_reset;
  wire i_reset;
  input i_write_fifo;
  wire i_write_fifo;
  output [7:0] o_data_to_read;
  wire [7:0] o_data_to_read;
  output o_fifo_is_empty;
  wire o_fifo_is_empty;
  output o_fifo_is_full;
  wire o_fifo_is_full;
  wire \read_ptr[0] ;
  wire \read_ptr[1] ;
  wire \write_ptr[0] ;
  wire \write_ptr[1] ;
  sky130_fd_sc_hd__inv_2 _065_ (
    .A(o_fifo_is_empty),
    .Y(_042_)
  );
  sky130_fd_sc_hd__inv_2 _066_ (
    .A(o_fifo_is_full),
    .Y(_043_)
  );
  sky130_fd_sc_hd__inv_2 _067_ (
    .A(i_write_fifo),
    .Y(_044_)
  );
  sky130_fd_sc_hd__mux4_2 _068_ (
    .A0(\array[0][0] ),
    .A1(\array[1][0] ),
    .A2(\array[2][0] ),
    .A3(\array[3][0] ),
    .S0(_000_),
    .S1(_001_),
    .X(o_data_to_read[0])
  );
  sky130_fd_sc_hd__mux4_2 _069_ (
    .A0(\array[0][1] ),
    .A1(\array[1][1] ),
    .A2(\array[2][1] ),
    .A3(\array[3][1] ),
    .S0(_000_),
    .S1(_001_),
    .X(o_data_to_read[1])
  );
  sky130_fd_sc_hd__mux4_2 _070_ (
    .A0(\array[0][2] ),
    .A1(\array[1][2] ),
    .A2(\array[2][2] ),
    .A3(\array[3][2] ),
    .S0(_000_),
    .S1(_001_),
    .X(o_data_to_read[2])
  );
  sky130_fd_sc_hd__mux4_2 _071_ (
    .A0(\array[0][3] ),
    .A1(\array[1][3] ),
    .A2(\array[2][3] ),
    .A3(\array[3][3] ),
    .S0(_000_),
    .S1(_001_),
    .X(o_data_to_read[3])
  );
  sky130_fd_sc_hd__mux4_2 _072_ (
    .A0(\array[0][4] ),
    .A1(\array[1][4] ),
    .A2(\array[2][4] ),
    .A3(\array[3][4] ),
    .S0(_000_),
    .S1(_001_),
    .X(o_data_to_read[4])
  );
  sky130_fd_sc_hd__mux4_2 _073_ (
    .A0(\array[0][5] ),
    .A1(\array[1][5] ),
    .A2(\array[2][5] ),
    .A3(\array[3][5] ),
    .S0(_000_),
    .S1(_001_),
    .X(o_data_to_read[5])
  );
  sky130_fd_sc_hd__mux4_2 _074_ (
    .A0(\array[0][6] ),
    .A1(\array[1][6] ),
    .A2(\array[2][6] ),
    .A3(\array[3][6] ),
    .S0(_000_),
    .S1(_001_),
    .X(o_data_to_read[6])
  );
  sky130_fd_sc_hd__mux4_2 _075_ (
    .A0(\array[0][7] ),
    .A1(\array[1][7] ),
    .A2(\array[2][7] ),
    .A3(\array[3][7] ),
    .S0(_000_),
    .S1(_001_),
    .X(o_data_to_read[7])
  );
  sky130_fd_sc_hd__nor2_2 _076_ (
    .A(o_fifo_is_full),
    .B(_044_),
    .Y(_045_)
  );
  sky130_fd_sc_hd__and3b_2 _077_ (
    .A_N(\write_ptr[0] ),
    .B(_045_),
    .C(\write_ptr[1] ),
    .X(_046_)
  );
  sky130_fd_sc_hd__mux2_1 _078_ (
    .A0(\array[2][0] ),
    .A1(i_data_to_write[0]),
    .S(_046_),
    .X(_002_)
  );
  sky130_fd_sc_hd__mux2_1 _079_ (
    .A0(\array[2][1] ),
    .A1(i_data_to_write[1]),
    .S(_046_),
    .X(_003_)
  );
  sky130_fd_sc_hd__mux2_1 _080_ (
    .A0(\array[2][2] ),
    .A1(i_data_to_write[2]),
    .S(_046_),
    .X(_004_)
  );
  sky130_fd_sc_hd__mux2_1 _081_ (
    .A0(\array[2][3] ),
    .A1(i_data_to_write[3]),
    .S(_046_),
    .X(_005_)
  );
  sky130_fd_sc_hd__mux2_1 _082_ (
    .A0(\array[2][4] ),
    .A1(i_data_to_write[4]),
    .S(_046_),
    .X(_006_)
  );
  sky130_fd_sc_hd__mux2_1 _083_ (
    .A0(\array[2][5] ),
    .A1(i_data_to_write[5]),
    .S(_046_),
    .X(_007_)
  );
  sky130_fd_sc_hd__mux2_1 _084_ (
    .A0(\array[2][6] ),
    .A1(i_data_to_write[6]),
    .S(_046_),
    .X(_008_)
  );
  sky130_fd_sc_hd__mux2_1 _085_ (
    .A0(\array[2][7] ),
    .A1(i_data_to_write[7]),
    .S(_046_),
    .X(_009_)
  );
  sky130_fd_sc_hd__or4_2 _086_ (
    .A(o_fifo_is_full),
    .B(\write_ptr[1] ),
    .C(\write_ptr[0] ),
    .D(_044_),
    .X(_047_)
  );
  sky130_fd_sc_hd__mux2_1 _087_ (
    .A0(i_data_to_write[0]),
    .A1(\array[0][0] ),
    .S(_047_),
    .X(_010_)
  );
  sky130_fd_sc_hd__mux2_1 _088_ (
    .A0(i_data_to_write[1]),
    .A1(\array[0][1] ),
    .S(_047_),
    .X(_011_)
  );
  sky130_fd_sc_hd__mux2_1 _089_ (
    .A0(i_data_to_write[2]),
    .A1(\array[0][2] ),
    .S(_047_),
    .X(_012_)
  );
  sky130_fd_sc_hd__mux2_1 _090_ (
    .A0(i_data_to_write[3]),
    .A1(\array[0][3] ),
    .S(_047_),
    .X(_013_)
  );
  sky130_fd_sc_hd__mux2_1 _091_ (
    .A0(i_data_to_write[4]),
    .A1(\array[0][4] ),
    .S(_047_),
    .X(_014_)
  );
  sky130_fd_sc_hd__mux2_1 _092_ (
    .A0(i_data_to_write[5]),
    .A1(\array[0][5] ),
    .S(_047_),
    .X(_015_)
  );
  sky130_fd_sc_hd__mux2_1 _093_ (
    .A0(i_data_to_write[6]),
    .A1(\array[0][6] ),
    .S(_047_),
    .X(_016_)
  );
  sky130_fd_sc_hd__mux2_1 _094_ (
    .A0(i_data_to_write[7]),
    .A1(\array[0][7] ),
    .S(_047_),
    .X(_017_)
  );
  sky130_fd_sc_hd__and3b_2 _095_ (
    .A_N(\write_ptr[1] ),
    .B(\write_ptr[0] ),
    .C(_045_),
    .X(_048_)
  );
  sky130_fd_sc_hd__mux2_1 _096_ (
    .A0(\array[1][0] ),
    .A1(i_data_to_write[0]),
    .S(_048_),
    .X(_018_)
  );
  sky130_fd_sc_hd__mux2_1 _097_ (
    .A0(\array[1][1] ),
    .A1(i_data_to_write[1]),
    .S(_048_),
    .X(_019_)
  );
  sky130_fd_sc_hd__mux2_1 _098_ (
    .A0(\array[1][2] ),
    .A1(i_data_to_write[2]),
    .S(_048_),
    .X(_020_)
  );
  sky130_fd_sc_hd__mux2_1 _099_ (
    .A0(\array[1][3] ),
    .A1(i_data_to_write[3]),
    .S(_048_),
    .X(_021_)
  );
  sky130_fd_sc_hd__mux2_1 _100_ (
    .A0(\array[1][4] ),
    .A1(i_data_to_write[4]),
    .S(_048_),
    .X(_022_)
  );
  sky130_fd_sc_hd__mux2_1 _101_ (
    .A0(\array[1][5] ),
    .A1(i_data_to_write[5]),
    .S(_048_),
    .X(_023_)
  );
  sky130_fd_sc_hd__mux2_1 _102_ (
    .A0(\array[1][6] ),
    .A1(i_data_to_write[6]),
    .S(_048_),
    .X(_024_)
  );
  sky130_fd_sc_hd__mux2_1 _103_ (
    .A0(\array[1][7] ),
    .A1(i_data_to_write[7]),
    .S(_048_),
    .X(_025_)
  );
  sky130_fd_sc_hd__o21a_2 _104_ (
    .A1(_042_),
    .A2(i_write_fifo),
    .B1(i_read_fifo),
    .X(_049_)
  );
  sky130_fd_sc_hd__o211a_2 _105_ (
    .A1(_042_),
    .A2(i_write_fifo),
    .B1(i_read_fifo),
    .C1(\read_ptr[0] ),
    .X(_050_)
  );
  sky130_fd_sc_hd__nor2_2 _106_ (
    .A(i_reset),
    .B(_050_),
    .Y(_051_)
  );
  sky130_fd_sc_hd__o21a_2 _107_ (
    .A1(\read_ptr[0] ),
    .A2(_049_),
    .B1(_051_),
    .X(_026_)
  );
  sky130_fd_sc_hd__a21oi_2 _108_ (
    .A1(\read_ptr[1] ),
    .A2(_050_),
    .B1(i_reset),
    .Y(_052_)
  );
  sky130_fd_sc_hd__o21a_2 _109_ (
    .A1(\read_ptr[1] ),
    .A2(_050_),
    .B1(_052_),
    .X(_027_)
  );
  sky130_fd_sc_hd__a211oi_2 _110_ (
    .A1(i_write_fifo),
    .A2(i_read_fifo),
    .B1(_045_),
    .C1(\write_ptr[0] ),
    .Y(_053_)
  );
  sky130_fd_sc_hd__o211a_2 _111_ (
    .A1(_043_),
    .A2(i_read_fifo),
    .B1(i_write_fifo),
    .C1(\write_ptr[0] ),
    .X(_054_)
  );
  sky130_fd_sc_hd__nor3_2 _112_ (
    .A(i_reset),
    .B(_053_),
    .C(_054_),
    .Y(_028_)
  );
  sky130_fd_sc_hd__a21oi_2 _113_ (
    .A1(\write_ptr[1] ),
    .A2(_054_),
    .B1(i_reset),
    .Y(_055_)
  );
  sky130_fd_sc_hd__o21a_2 _114_ (
    .A1(\write_ptr[1] ),
    .A2(_054_),
    .B1(_055_),
    .X(_029_)
  );
  sky130_fd_sc_hd__a31o_2 _115_ (
    .A1(_042_),
    .A2(_044_),
    .A3(i_read_fifo),
    .B1(_043_),
    .X(_056_)
  );
  sky130_fd_sc_hd__xnor2_2 _116_ (
    .A(\write_ptr[1] ),
    .B(\write_ptr[0] ),
    .Y(_057_)
  );
  sky130_fd_sc_hd__xnor2_2 _117_ (
    .A(\read_ptr[1] ),
    .B(_057_),
    .Y(_058_)
  );
  sky130_fd_sc_hd__xnor2_2 _118_ (
    .A(\read_ptr[0] ),
    .B(\write_ptr[0] ),
    .Y(_059_)
  );
  sky130_fd_sc_hd__or4_2 _119_ (
    .A(_044_),
    .B(i_read_fifo),
    .C(_058_),
    .D(_059_),
    .X(_060_)
  );
  sky130_fd_sc_hd__a21oi_2 _120_ (
    .A1(_056_),
    .A2(_060_),
    .B1(i_reset),
    .Y(_032_)
  );
  sky130_fd_sc_hd__or3_2 _121_ (
    .A(o_fifo_is_full),
    .B(_044_),
    .C(i_read_fifo),
    .X(_061_)
  );
  sky130_fd_sc_hd__nor3b_2 _122_ (
    .A(i_write_fifo),
    .B(_059_),
    .C_N(i_read_fifo),
    .Y(_062_)
  );
  sky130_fd_sc_hd__a21o_2 _123_ (
    .A1(_058_),
    .A2(_062_),
    .B1(o_fifo_is_empty),
    .X(_063_)
  );
  sky130_fd_sc_hd__a21o_2 _124_ (
    .A1(_061_),
    .A2(_063_),
    .B1(i_reset),
    .X(_033_)
  );
  sky130_fd_sc_hd__and3_2 _125_ (
    .A(\write_ptr[1] ),
    .B(\write_ptr[0] ),
    .C(_045_),
    .X(_064_)
  );
  sky130_fd_sc_hd__mux2_1 _126_ (
    .A0(\array[3][0] ),
    .A1(i_data_to_write[0]),
    .S(_064_),
    .X(_034_)
  );
  sky130_fd_sc_hd__mux2_1 _127_ (
    .A0(\array[3][1] ),
    .A1(i_data_to_write[1]),
    .S(_064_),
    .X(_035_)
  );
  sky130_fd_sc_hd__mux2_1 _128_ (
    .A0(\array[3][2] ),
    .A1(i_data_to_write[2]),
    .S(_064_),
    .X(_036_)
  );
  sky130_fd_sc_hd__mux2_1 _129_ (
    .A0(\array[3][3] ),
    .A1(i_data_to_write[3]),
    .S(_064_),
    .X(_037_)
  );
  sky130_fd_sc_hd__mux2_1 _130_ (
    .A0(\array[3][4] ),
    .A1(i_data_to_write[4]),
    .S(_064_),
    .X(_038_)
  );
  sky130_fd_sc_hd__mux2_1 _131_ (
    .A0(\array[3][5] ),
    .A1(i_data_to_write[5]),
    .S(_064_),
    .X(_039_)
  );
  sky130_fd_sc_hd__mux2_1 _132_ (
    .A0(\array[3][6] ),
    .A1(i_data_to_write[6]),
    .S(_064_),
    .X(_040_)
  );
  sky130_fd_sc_hd__mux2_1 _133_ (
    .A0(\array[3][7] ),
    .A1(i_data_to_write[7]),
    .S(_064_),
    .X(_041_)
  );
  sky130_fd_sc_hd__o21a_2 _134_ (
    .A1(\read_ptr[0] ),
    .A2(_049_),
    .B1(_051_),
    .X(_030_)
  );
  sky130_fd_sc_hd__o21a_2 _135_ (
    .A1(\read_ptr[1] ),
    .A2(_050_),
    .B1(_052_),
    .X(_031_)
  );
  sky130_fd_sc_hd__dfxtp_2 _136_ (
    .CLK(i_clk),
    .D(_002_),
    .Q(\array[2][0] )
  );
  sky130_fd_sc_hd__dfxtp_2 _137_ (
    .CLK(i_clk),
    .D(_003_),
    .Q(\array[2][1] )
  );
  sky130_fd_sc_hd__dfxtp_2 _138_ (
    .CLK(i_clk),
    .D(_004_),
    .Q(\array[2][2] )
  );
  sky130_fd_sc_hd__dfxtp_2 _139_ (
    .CLK(i_clk),
    .D(_005_),
    .Q(\array[2][3] )
  );
  sky130_fd_sc_hd__dfxtp_2 _140_ (
    .CLK(i_clk),
    .D(_006_),
    .Q(\array[2][4] )
  );
  sky130_fd_sc_hd__dfxtp_2 _141_ (
    .CLK(i_clk),
    .D(_007_),
    .Q(\array[2][5] )
  );
  sky130_fd_sc_hd__dfxtp_2 _142_ (
    .CLK(i_clk),
    .D(_008_),
    .Q(\array[2][6] )
  );
  sky130_fd_sc_hd__dfxtp_2 _143_ (
    .CLK(i_clk),
    .D(_009_),
    .Q(\array[2][7] )
  );
  sky130_fd_sc_hd__dfxtp_2 _144_ (
    .CLK(i_clk),
    .D(_010_),
    .Q(\array[0][0] )
  );
  sky130_fd_sc_hd__dfxtp_2 _145_ (
    .CLK(i_clk),
    .D(_011_),
    .Q(\array[0][1] )
  );
  sky130_fd_sc_hd__dfxtp_2 _146_ (
    .CLK(i_clk),
    .D(_012_),
    .Q(\array[0][2] )
  );
  sky130_fd_sc_hd__dfxtp_2 _147_ (
    .CLK(i_clk),
    .D(_013_),
    .Q(\array[0][3] )
  );
  sky130_fd_sc_hd__dfxtp_2 _148_ (
    .CLK(i_clk),
    .D(_014_),
    .Q(\array[0][4] )
  );
  sky130_fd_sc_hd__dfxtp_2 _149_ (
    .CLK(i_clk),
    .D(_015_),
    .Q(\array[0][5] )
  );
  sky130_fd_sc_hd__dfxtp_2 _150_ (
    .CLK(i_clk),
    .D(_016_),
    .Q(\array[0][6] )
  );
  sky130_fd_sc_hd__dfxtp_2 _151_ (
    .CLK(i_clk),
    .D(_017_),
    .Q(\array[0][7] )
  );
  sky130_fd_sc_hd__dfxtp_2 _152_ (
    .CLK(i_clk),
    .D(_018_),
    .Q(\array[1][0] )
  );
  sky130_fd_sc_hd__dfxtp_2 _153_ (
    .CLK(i_clk),
    .D(_019_),
    .Q(\array[1][1] )
  );
  sky130_fd_sc_hd__dfxtp_2 _154_ (
    .CLK(i_clk),
    .D(_020_),
    .Q(\array[1][2] )
  );
  sky130_fd_sc_hd__dfxtp_2 _155_ (
    .CLK(i_clk),
    .D(_021_),
    .Q(\array[1][3] )
  );
  sky130_fd_sc_hd__dfxtp_2 _156_ (
    .CLK(i_clk),
    .D(_022_),
    .Q(\array[1][4] )
  );
  sky130_fd_sc_hd__dfxtp_2 _157_ (
    .CLK(i_clk),
    .D(_023_),
    .Q(\array[1][5] )
  );
  sky130_fd_sc_hd__dfxtp_2 _158_ (
    .CLK(i_clk),
    .D(_024_),
    .Q(\array[1][6] )
  );
  sky130_fd_sc_hd__dfxtp_2 _159_ (
    .CLK(i_clk),
    .D(_025_),
    .Q(\array[1][7] )
  );
  sky130_fd_sc_hd__dfxtp_2 _160_ (
    .CLK(i_clk),
    .D(_026_),
    .Q(_000_)
  );
  sky130_fd_sc_hd__dfxtp_2 _161_ (
    .CLK(i_clk),
    .D(_027_),
    .Q(_001_)
  );
  sky130_fd_sc_hd__dfxtp_2 _162_ (
    .CLK(i_clk),
    .D(_028_),
    .Q(\write_ptr[0] )
  );
  sky130_fd_sc_hd__dfxtp_2 _163_ (
    .CLK(i_clk),
    .D(_029_),
    .Q(\write_ptr[1] )
  );
  sky130_fd_sc_hd__dfxtp_2 _164_ (
    .CLK(i_clk),
    .D(_030_),
    .Q(\read_ptr[0] )
  );
  sky130_fd_sc_hd__dfxtp_2 _165_ (
    .CLK(i_clk),
    .D(_031_),
    .Q(\read_ptr[1] )
  );
  sky130_fd_sc_hd__dfxtp_2 _166_ (
    .CLK(i_clk),
    .D(_032_),
    .Q(o_fifo_is_full)
  );
  sky130_fd_sc_hd__dfxtp_2 _167_ (
    .CLK(i_clk),
    .D(_033_),
    .Q(o_fifo_is_empty)
  );
  sky130_fd_sc_hd__dfxtp_2 _168_ (
    .CLK(i_clk),
    .D(_034_),
    .Q(\array[3][0] )
  );
  sky130_fd_sc_hd__dfxtp_2 _169_ (
    .CLK(i_clk),
    .D(_035_),
    .Q(\array[3][1] )
  );
  sky130_fd_sc_hd__dfxtp_2 _170_ (
    .CLK(i_clk),
    .D(_036_),
    .Q(\array[3][2] )
  );
  sky130_fd_sc_hd__dfxtp_2 _171_ (
    .CLK(i_clk),
    .D(_037_),
    .Q(\array[3][3] )
  );
  sky130_fd_sc_hd__dfxtp_2 _172_ (
    .CLK(i_clk),
    .D(_038_),
    .Q(\array[3][4] )
  );
  sky130_fd_sc_hd__dfxtp_2 _173_ (
    .CLK(i_clk),
    .D(_039_),
    .Q(\array[3][5] )
  );
  sky130_fd_sc_hd__dfxtp_2 _174_ (
    .CLK(i_clk),
    .D(_040_),
    .Q(\array[3][6] )
  );
  sky130_fd_sc_hd__dfxtp_2 _175_ (
    .CLK(i_clk),
    .D(_041_),
    .Q(\array[3][7] )
  );
endmodule

module top(i_clk, i_reset, i_uartRx, o_uartTx);
  wire \alu_op_A[0] ;
  wire \alu_op_A[1] ;
  wire \alu_op_A[2] ;
  wire \alu_op_A[3] ;
  wire \alu_op_A[4] ;
  wire \alu_op_A[5] ;
  wire \alu_op_A[6] ;
  wire \alu_op_A[7] ;
  wire \alu_op_B[0] ;
  wire \alu_op_B[1] ;
  wire \alu_op_B[2] ;
  wire \alu_op_B[3] ;
  wire \alu_op_B[4] ;
  wire \alu_op_B[5] ;
  wire \alu_op_B[6] ;
  wire \alu_op_B[7] ;
  wire \alu_opcode[0] ;
  wire \alu_opcode[1] ;
  wire \alu_opcode[2] ;
  wire \alu_opcode[3] ;
  wire \alu_opcode[4] ;
  wire \alu_opcode[5] ;
  wire \alu_result[0] ;
  wire \alu_result[1] ;
  wire \alu_result[2] ;
  wire \alu_result[3] ;
  wire \alu_result[4] ;
  wire \alu_result[5] ;
  wire \alu_result[6] ;
  wire \alu_result[7] ;
  wire \data_to_read[0] ;
  wire \data_to_read[1] ;
  wire \data_to_read[2] ;
  wire \data_to_read[3] ;
  wire \data_to_read[4] ;
  wire \data_to_read[5] ;
  wire \data_to_read[6] ;
  wire \data_to_read[7] ;
  wire \data_to_write[0] ;
  wire \data_to_write[1] ;
  wire \data_to_write[2] ;
  wire \data_to_write[3] ;
  wire \data_to_write[4] ;
  wire \data_to_write[5] ;
  wire \data_to_write[6] ;
  wire \data_to_write[7] ;
  input i_clk;
  wire i_clk;
  input i_reset;
  wire i_reset;
  input i_uartRx;
  wire i_uartRx;
  output o_uartTx;
  wire o_uartTx;
  wire rx_empty;
  wire rx_read;
  wire tx_full;
  wire tx_write;
  \$paramod$1b78d2d521b3f5ebabffb07db7e6e88fe1f0b213\alu  aluUnit (
    .i_data_a({ \alu_op_A[7] , \alu_op_A[6] , \alu_op_A[5] , \alu_op_A[4] , \alu_op_A[3] , \alu_op_A[2] , \alu_op_A[1] , \alu_op_A[0]  }),
    .i_data_b({ \alu_op_B[7] , \alu_op_B[6] , \alu_op_B[5] , \alu_op_B[4] , \alu_op_B[3] , \alu_op_B[2] , \alu_op_B[1] , \alu_op_B[0]  }),
    .i_op({ \alu_opcode[5] , \alu_opcode[4] , \alu_opcode[3] , \alu_opcode[2] , \alu_opcode[1] , \alu_opcode[0]  }),
    .o_alu_result({ \alu_result[7] , \alu_result[6] , \alu_result[5] , \alu_result[4] , \alu_result[3] , \alu_result[2] , \alu_result[1] , \alu_result[0]  })
  );
  \$paramod$3657eea4d53669bfdbf8ea094d48a5708f5ac2cf\alu_uart_interface  alu_uart_interfaceUnit (
    .i_alu_result({ \alu_result[7] , \alu_result[6] , \alu_result[5] , \alu_result[4] , \alu_result[3] , \alu_result[2] , \alu_result[1] , \alu_result[0]  }),
    .i_clk(i_clk),
    .i_data_to_read({ \data_to_read[7] , \data_to_read[6] , \data_to_read[5] , \data_to_read[4] , \data_to_read[3] , \data_to_read[2] , \data_to_read[1] , \data_to_read[0]  }),
    .i_fifo_rx_empty(rx_empty),
    .i_fifo_tx_full(tx_full),
    .i_reset(i_reset),
    .o_alu_op_A({ \alu_op_A[7] , \alu_op_A[6] , \alu_op_A[5] , \alu_op_A[4] , \alu_op_A[3] , \alu_op_A[2] , \alu_op_A[1] , \alu_op_A[0]  }),
    .o_alu_op_B({ \alu_op_B[7] , \alu_op_B[6] , \alu_op_B[5] , \alu_op_B[4] , \alu_op_B[3] , \alu_op_B[2] , \alu_op_B[1] , \alu_op_B[0]  }),
    .o_alu_opcode({ \alu_opcode[5] , \alu_opcode[4] , \alu_opcode[3] , \alu_opcode[2] , \alu_opcode[1] , \alu_opcode[0]  }),
    .o_data_to_write({ \data_to_write[7] , \data_to_write[6] , \data_to_write[5] , \data_to_write[4] , \data_to_write[3] , \data_to_write[2] , \data_to_write[1] , \data_to_write[0]  }),
    .o_fifo_rx_read(rx_read),
    .o_fifo_tx_write(tx_write)
  );
  \$paramod$6b4111703c44ac05de92b2879f439a7cdf507670\uart_interface  uartUnit (
    .i_clk(i_clk),
    .i_data_to_write({ \data_to_write[7] , \data_to_write[6] , \data_to_write[5] , \data_to_write[4] , \data_to_write[3] , \data_to_write[2] , \data_to_write[1] , \data_to_write[0]  }),
    .i_read_uart(rx_read),
    .i_reset(i_reset),
    .i_rx(i_uartRx),
    .i_write_uart(tx_write),
    .o_data_to_read({ \data_to_read[7] , \data_to_read[6] , \data_to_read[5] , \data_to_read[4] , \data_to_read[3] , \data_to_read[2] , \data_to_read[1] , \data_to_read[0]  }),
    .o_rx_empty(rx_empty),
    .o_tx(o_uartTx),
    .o_tx_full(tx_full)
  );
endmodule
